#main_section > lines > line > text
#main_section > lines > line > sub_line > text
#main_section > sub_sections
#main_section > templates > type
#main_section > templates > empty_values
#main_section > templates > values
#main_section > templates > sub_templates
#main_section > title > line > text
from transformers.models.auto import configuration_auto
from model.quote import *

languages_with_templates=["fr","da","nl","be","is","ca","bg","da","ka"]
hybrid_languages = ["uk","ru","sv","et"] + ["ko","fa","cs","fi", "hy"]

misattributed = {
    'ar': ['ضعيف', 'متنازع عليه', 'بشكل غير صحيح', 'قائلا نعزى خطأ', 'يعزى خطأ إلى', 'ونقلت تم تعيينها', 'إساءة', 'نعزى بشكل غير صحيح', 'متصل بشكل غير صحيح', 'يعزى بشكل غير صحيح إلى', 'مثيرة للجدل', 'تم تعيينه بشكل غير صحيح', 'تم تعيينه بشكل غير صحيح', 'الفضل بشكل غير صحيح', 'مشكوك فيه', 'سوء المعاملة', 'سيئة', 'خاطئ', 'الفضل بشكل خاطئ', 'لم يتم التحقق منه', 'مرفقة بشكل غير صحيح', 'الفضل بشكل غير صحيح', 'غير صحيح', 'يعزى إلى الخطأ', 'مشبوه أو مشكوك فيه'],\
    'az': ['zəif', 'mübahisəli', 'yanlış', 'yanlış şəkildə aid olduğunu söyləmək', 'səhv yanına aiddir', 'Təyin olunmuş sitatlar', 'yanılsaq', 'səhv aiddir', 'səhv bağlıdır', 'səhv aiddir', 'mübahisəli', 'səhv təyin olunur', 'səhv təyin olunmuşdur', 'səhv hesablanır', 'şübhəli', 'zəif', 'səhv', 'səhv hesablanır', 'təsdiqlənməmiş', 'səhv əlavə olunur', 'səhv hesablanır', 'yanlış', 'səhvən aiddir', 'şübhəli'],\
    'be': ['слабы', 'спрэчны', 'няправільна', 'кажучы няправільна прыпісаны', 'памылкова звязаны з', 'Цытаты прызначаныя', 'misatributed', 'няправільна прыпісваецца', 'няправільна падлучаны', 'няправільна прыпісваецца', 'супярэчлівы', 'няправільна прызначаны', 'няправільна прызначаны', 'залічваецца няправільна', 'няпэўны', 'адварочваў', 'кепска', 'памылковы', 'памылкова залічана', 'неўверыў', 'няправільна прыкладаецца', 'няправільна залічаны', 'няправільны', 'прыпісваецца памылкова', 'падазроны'],\
    'bg': ['слаб', 'оспорван', 'неправилно', 'казвайки погрешно приписване', 'погрешно се приписва', 'Misattributed.', 'неправилно приписано', 'неправилно свързани', 'неправилно', 'противоречиви', 'е неправилно назначен', 'неправилно зададен', 'кредитирани неправилно', 'съмнително', 'Млъкни', 'лошо', 'погрешно', 'неправилно кредитирани', 'Несъвършен', 'неправилно прикрепени', 'неправилно кредитирани', 'неправилен', 'се приписва на погрешно', 'подозрителен'],\
    'bs': ['slab', 'sporan', 'pogrešno', 'govoreći pogrešno pripisano', 'pogrešno se pripisuje', 'Citati dodijeljene', 'misao', 'Netačno pripisan', 'Nepravilno povezani', 'pogrešno pripisan', 'kontroverzan', 'pogrešno je dodeljen', 'pogrešno dodijeljeno', 'pripisuju pogrešno', 'sumnjiv', 'maltretiran', 'slabo', 'pogrešno', 'pogrešno pripisan', 'neprovjeren', 'pogrešno priložen', 'pogrešno pripisan', 'netačan', 'pripisuje se pogrešno', 'sumnjiv'], \
    'ca': ['feble', 'en disputa', 'incorrectament', 'dient incorrectament atribuït', "s'atribueix incorrectament a", 'Cotitzacions assignades', 'Misattributed', 'atribuïts incorrectament', 'connectat incorrectament', 'atribuït incorrectament a', 'controvertit', 'està assignat incorrectament', 'assignat incorrectament', 'acreditat incorrectament', 'dubtós', 'maltractat', 'pobrament', 'mal', 'acreditat incorrectament', 'no verificat', 'incorrectament adjunt', 'acreditat incorrectament', 'incorrecte', "s'atribueix a erròniament", 'sospitós'], \
    'co': ['debuli', 'disputa', 'sbagliatu', 'dicendu attribuitu sbagliatu', 'sbagliatu hè attribuita à', 'Quotes assignati', 'misattribuitu', 'attribuitu sbagliatu', 'cunnessu sbagliatu', 'attribuitu sbagliatu à', 'cuntruversuale', 'hè incorrectamente assignatu', 'assignatu sbagliatu', 'creditu sbagliatu', 'dubbitu', 'MISTORATU', 'Poviru', 'sbagliatu', 'sbagliatu creditu', 'Unvererazionatu', 'sbagliatu attaccatu', 'incorrectamente creditu', 'sbagliatu', 'hè attribuita à sbaglià', 'suspicosu'],\
    "cs": ['pochybný', 'nesprávně je připisován', 'je přičítán omylem', 'neosgejavané.', 'říká se nesprávně přiřazené', 'sporný', 'je nesprávně přiřazen', 'špatně', 'nesprávně připojeno', 'nesprávně', 'nezbytný', 'nesprávně přiřazeno', 'nesprávně přisuzováno', 'špatně zacházený', 'slabý', 'nesprávný', 'nesprávně připsány', 'nesprávně připsaný', 'přidělené nabídky', 'podezřelý', 'neověřené'],\
    'da': ['svag', 'bestridt', 'forkert', 'siger fejlagtigt tilskrevet', 'fejlagtigt tilskrives', 'citater tildelt', 'misattributed.', 'forkert tilskrevet', 'forkert forbundet', 'forkert tilskrives', 'kontroversielt', 'er forkert tildelt', 'forkert tildelt', 'krediteret forkert', 'tvivlsom', 'mishandlet', 'Dårlig', 'forkert', 'fejlagtigt krediteret', 'unverified.', 'forkert vedhæftet', 'forkert krediteret', 'ukorrekt', 'er tilskrevet fejlagtigt', 'mistænksom'], \
    "de": ['falsch verbunden', 'falsch angebracht', 'falsch zugewiesen', 'wird fehlerhaft zurückgeführt', 'schwach', 'fälschlich zugeschrieben', 'falsch zugerechnet', 'falsch wird zugeschrieben', 'falsch', 'falsch angeschlossen', 'misshandelt', 'unrecht zugeschrieben werden', 'misstrauisch', 'falsch gutgeschrieben', 'zweifelhaft', 'ist falsch zugewiesen', 'notwendig', 'zitate zugewiesen', 'nicht verifiziert'],\
    'el': ['αδύναμος', 'αμφισβητούμενος', 'εσφαλμένα', 'λέγοντας εσφαλμένα αποδόσεις', 'λανθασμένα αποδίδεται σε', 'αποσπάσματα', 'απροσδόκητος', 'που αποδίδονται εσφαλμένα', 'εσφαλμένα συνδεδεμένο', 'που αποδοθεί εσφαλμένα', 'αμφιλεγόμενος', 'έχει ανατεθεί εσφαλμένα', 'εσφαλμένα αποδίδεται', 'πιστώθηκε λανθασμένα', 'αμφίβολος', 'κακομεταχειρίζομαι', 'πτωχώς', 'λανθασμένος', 'λάθος πιστώθηκε', 'ανεπιβεβαίωτος', 'Επισυνάπτεται εσφαλμένα', 'εσφαλμένα πιστώνεται', 'ανακριβής', 'αποδίδεται λανθασμένα', 'ύποπτος'],\
    "en": ['weak', 'disputed', 'incorrectly', 'saying wrongly attributed', 'wrongly is attributed to', 'quotes assigned', 'misattributed', 'incorrectly attributed', 'incorrectly connected', 'incorrectly attributed to', 'controversial', 'is incorrectly assigned', 'incorrectly assigned', 'credited incorrectly', 'doubtful', 'mistreated', 'poorly', 'wrong', 'wrongly credited', 'unverified', 'incorrectly attached', 'incorrectly credited', 'incorrect', 'is attributed to mistakenly', 'suspicious'],\
    "es": ['débil', 'disputado', 'incorrectamente', 'decir atribuido incorrectamente', 'atribuido incorrectamente a', 'citas asignadas', 'atribuido incorrectamente', 'atribuido incorrectamente', 'conectado incorrectamente', ' atribuido incorrectamente a ',' controvertido ',' asignado incorrectamente ',' asignado incorrectamente ',' acreditado incorrectamente ',' dudoso ',' maltratado ',' mal ',' incorrecto ',' acreditado incorrectamente ',' no verificado ', 'adjunto incorrectamente', 'acreditado incorrectamente', 'incorrecto', 'atribuido erróneamente', 'sospechoso'],\
    'et': ['nõrk', 'vaidlustatud', 'valesti', 'öeldes valesti omistatud', 'valesti omistatakse', 'määratud hinnapakkumisi', 'eksima', 'valesti omistatud', 'valesti ühendatud', 'valesti omistatud', 'vastuoluline', 'on valesti määratud', 'valesti määratud', 'krediteeritud valesti', 'kahtlane', 'väärkohtlemine', 'halvasti', 'vale', 'valesti krediteeritud', 'vastamata jätmine', 'valesti kinnitatud', 'valesti krediteeritud', 'vale', 'omistatakse ekslikult', 'kahtlane'],\
    'eu': ['ahul', 'jokatu', 'gaizki', 'gaizki egozten esanda', 'gaizki egozten zaio', 'esleitutako aipuak', 'Misattributatua', 'oker egotzi', 'Gaizki konektatuta', 'oker egotzita', 'Polemika', 'gaizki esleitzen da', 'gaizki esleituta', 'oker kreditua', 'zalantzazko', 'tratu txarrak', 'txarto', 'okerreko', 'gaizki kreditatu', 'irentetu gabe', 'oker erantsita', 'Gaizki kreditatu', 'ez zuzen', 'oker egozten zaio', 'goganbehartsu'],\
    'fa': ['ضعیف', 'متضاد', 'نادرست', 'گفتن اشتباه است', 'اشتباه به آن نسبت داده می شود', 'نقل قول اختصاص داده شده', 'سوء تفاهم', 'نادرست نسبت داده شده است', 'نادرست متصل است', 'نادرست به', 'بحث برانگیز', 'نادرست اختصاص داده شده است', 'اشتباه اختصاص داده شده است', 'اعتبار نادرست', 'مشکوک', 'بدرفتاری', 'ضعیف', 'اشتباه', 'اشتباه اعتبار', 'غیر قابل تایید', 'اشتباه متصل شده', 'اشتباه اعتبار', 'غلط', 'به اشتباه نسبت داده شده است', 'مشکوک'],\
    'fi': ['heikko', 'kiistanalainen', 'väärin', 'sanomalla väärin', 'virheellisesti johtuu', 'Lainaukset', 'huonosti', 'virheellisesti', 'Väärin kytketty', 'virheellisesti', 'kiistanalainen', 'on asetettu virheellisesti', 'Virheellisesti määritetty', 'hyvitetään väärin', 'epäilyttävä', 'kohteliaisuus', 'huonosti', 'väärä', 'Väärin hyvitetty', 'vahvistettu', 'Virheellisesti kiinnitetty', 'Virheellisesti hyvitetty', 'väärä', 'johtuu virheellisesti', 'epäilyttävä'],\
    'fr': ['faible', 'contesté', 'incorrectement', 'dire attribué à tort', 'est attribué à tort à', 'citations attribuées', 'mal attribué', 'mal attribué', 'incorrectement connecté', ' attribué à tort à', 'controversé', 'est attribué de manière incorrecte', 'attribué de manière incorrecte', 'crédité de manière incorrecte', 'douteux', 'maltraité', 'mal', 'mauvais', 'crédité à tort', 'non vérifié', 'incorrectement joint', 'mal crédité', 'incorrect', 'est attribué à tort', 'suspect'],\
    'he': ['חלש', 'משווקת', 'לא נכון', 'אומר מיוחסת בטעות', 'בטעות מיוחסת', 'ציטוטים שהוקצו', 'misattributed', 'המיוחס בצורה שגויה', 'קשור באופן שגוי', 'המיוחס לא נכון', 'שנוי במחלוקת', 'מוקצה באופן שגוי', 'שהוקצו באופן שגוי', 'זוכה באופן שגוי', 'מוטל בספק', 'התעללות', 'גרוע', 'שגוי', 'שזוכו בטעות', 'unverified', 'המצורפת באופן שגוי', 'זוכה לא נכון', 'לֹא נָכוֹן', 'מיוחסת לטעות בטעות', 'חָשׁוּד'], 'hi': ['कमज़ोर', 'विवादित', 'गलत तरीके से', 'गलत तरीके से कहना', 'गलत तरीके से जिम्मेदार है', 'उद्धरण सौंपा', 'गलत', 'गलत तरीके से जिम्मेदार', 'गलत तरीके से जुड़ा हुआ', 'गलत तरीके से जिम्मेदार ठहराया', 'विवादास्पद', 'गलत तरीके से सौंपा गया है', 'गलत तरीके से असाइन किया गया', 'गलत तरीके से श्रेय दिया गया', 'संदिग्ध', 'दुराचारित', 'बीमार', 'गलत', 'गलत तरीके से श्रेय दिया गया', 'असत्यापित', 'गलत तरीके से संलग्न', 'गलत तरीके से श्रेय दिया गया', 'ग़लत', 'गलती से जिम्मेदार है', 'संदेहजनक'],\
    'hr': ['slab', 'osporen', 'nepravilno', 'govoreći pogrešno pripisuje se', 'pogrešno se pripisuje', 'dodijeljeni citati', 'pogrešan', 'Neispravno se pripisuje', 'pogrešno povezan', 'pogrešno pripisuje', 'kontroverzno', 'je pogrešno dodijeljen', 'pogrešno dodijeljen', 'pogrešno pripisano', 'sumnjiv', 'maltretiran', 'slabo', 'pogrešno', 'pogrešno pripisano', 'neveritičan', 'pogrešno pričvršćen', 'pogrešno pripisano', 'netočno', 'se pripisuje pogrešno', 'sumnjičav'],\
    'hu': ['gyenge', 'vitatott', 'tévesen', 'rosszul mondván', 'helytelenül tulajdonítható', 'Idézetek hozzárendeltek', 'félreérthetetlen', 'helytelenül tulajdonítható', 'Helytelenül csatlakoztatva van', 'helytelenül tulajdonítható', 'vitatott', 'helytelenül hozzárendelt', 'Helytelenül hozzárendelt', 'helytelenül jóváírják', 'kétséges', 'rosszul kezelt', 'rosszul', 'rossz', 'tévesen jóváírta', 'ellenőrizetlen', 'Helytelenül csatolt', 'helytelenül jóváírta', 'helytelen', 'tévesen tulajdonítható', 'gyanús'],\
    'hy': ['թույլ', 'վիճված', 'սխալ', 'սխալ ասելով, վերագրվում է', 'սխալ է վերագրվում', 'Նշված մեջբերումները', 'Մատսել է', 'Սխալ կերպով վերագրվում է', 'Սխալ միացված', 'սխալ է վերագրվել', 'վիճաբանական', 'սխալ է նշանակվել', 'Սխալ նշանակված', 'սխալվել է սխալ', 'կասկածելի', 'չարամտել', 'վատ', 'սխալ', 'սխալվել է', 'անավարտ', 'Սխալորեն կցված', 'սխալ է գնահատվել', 'սխալ', 'վերագրվում է սխալմամբ', 'կասկածելի'],\
    'id': ['lemah', 'diperdebatkan', 'salah', 'mengatakan salah dikaitkan.', 'salah dikaitkan dengan', 'Kutipan ditugaskan', 'salah penyibaran', 'salah dikaitkan', 'salah terhubung', 'salah dikaitkan dengannya', 'kontroversial', 'salah ditugaskan', 'salah ditugaskan', 'dikreditkan secara salah', 'diragukan lagi', 'Dianiaya', 'buruk', 'salah', 'salah dikreditkan', 'tidak diverifikasi', 'salah melekat', 'salah dikreditkan', 'salah', 'dikaitkan dengan keliru', 'mencurigakan'],\
    'is': ['veik', 'umdeildur', 'rangt', 'segja að ranglega rekja til', 'rangt stafar af', 'Tilvitnanir úthlutað', 'misertributed.', 'rangt rekja má', 'rangt tengt', 'rangt rekja til', 'umdeild', 'er rangt úthlutað', 'rangt úthlutað', 'lögð rangt', 'efast', 'mistreated.', 'illa', 'rangt', 'ranglega lögð inn', 'unverfied.', 'rangt fylgir', 'Rangt viðurkennt', 'rangt', 'er rekja til ranglega', 'grunsamlegt'],\
    'it': ['debole', 'disputato', 'erroneamente', 'detto erroneamente attribuito', 'erroneamente attribuito a', 'virgolette assegnate', 'erroneamente attribuito', 'erroneamente attribuito', 'erroneamente connesso', ' erroneamente attribuito a', 'controverso', 'è assegnato in modo errato', 'assegnato in modo errato', 'accreditato in modo errato', 'dubbio', 'maltrattato', 'male', 'sbagliato', 'accreditato erroneamente', 'non verificato', 'erroneamente allegato', 'erroneamente accreditato', 'errato', 'è attribuito a erroneamente', 'sospetto'],\
    'ja': ['弱い', '議論した', '誤って', '間違って帰ったことを言っています', '間違って帰属しています', '割り当てられた引用符', '誤動作しました', '間違って帰属しました', '誤って接続されています', '誤って帰属しました', '物議を醸す', '間違って割り当てられています', '間違って割り当てられています', '誤って入金されました', '疑わしい', '虐待された', '不完全に', '間違い', '間違ってクレジットされました', '未検証', '誤って添付されています', '誤ってクレジットされました', '正しくない', '誤って帰属されています', '疑わしい'],\
    'ka': ['სუსტი', 'სადავო', 'არასწორად', 'არასწორად მიეკუთვნება', 'არასწორად მიეკუთვნება', 'შეთავაზებები', 'misattributed', 'არასწორად მიეკუთვნება', 'არასწორად უკავშირდება', 'არასწორად მიეკუთვნება', 'დროებითი', 'არასწორად არის მინიჭებული', 'არასწორად მინიჭებული', 'არასწორად დაკრედიტდება', 'საეჭვო', 'mistreated', 'ღარიბად', 'მცდარი', 'არასწორად დაკრედიტდება', 'გადაუსებული', 'არასწორად ერთვის', 'არასწორად დაკრედიტდება', 'არასწორი', 'შეცდომით მიეკუთვნება', 'საეჭვო'],\
    'ko': ['약한', '분쟁', '틀리게', '잘못된 것으로 말하고있다', '잘못된 것은', '할당 된 따옴표', '미해시', '잘못된 것으로 잘못된 것입니다', '잘못 연결되었습니다', '잘못된 것으로 잘못된 것입니다', '논란이 많은', '잘못 지정됩니다', '잘못 지정되었습니다', '잘못 적립되었습니다', '불안한', '학대하다', '신통치 않게', '잘못된', '잘못된 적립 된 것', '확인되지 않았습니다', '잘못 첨부되었습니다', '잘못 적립되었습니다', '잘못된', '실수로 기인합니다', '의심스러운'],\
    'lt': ['Silpnas', 'ginčijama', 'Neteisingai', 'sakydamas neteisingai priskirtas', 'neteisingai priskiriama', 'Citatos', 'nesuderinta', 'neteisingai priskiriama', 'neteisingai prijungta', 'neteisingai priskirta', 'prieštaringas', 'yra neteisingai priskirtas', 'neteisingai priskirtas', 'neteisingai įskaityta', 'abejotina', 'netinkamai elgiamasi', 'blogai', 'neteisingas', 'neteisingai įskaityta', 'nepatvirtinta', 'neteisingai prijungtas', 'neteisingai įskaityta', 'Neteisinga', 'priskiriama klaidingai', 'įtartinas'],\
    'nl': ['zwak', 'twijfelachtig', 'onjuist', 'Samenstellen ten onrechte toegeschreven', 'ten onrechte wordt toegeschreven aan', 'Citaten toegewezen', 'verkeerd ingesteld', 'Onjuist toegeschreven', 'Onjuist aangesloten', 'onjuist toegeschreven aan', 'controverseel', 'is verkeerd toegewezen', 'Onjuist toegewezen', 'verkeerd gecrediteerd', 'twijfelachtig', 'mishandeld', 'slecht', 'mis', 'ten onrechte gecrediteerd', 'ongehroken', 'verkeerd bevestigd', 'onjuist gecrediteerd', 'niet correct', 'wordt toegeschreven aan ten onrechte', 'verdacht'],\
    'no': ['svak', 'omstridt', 'feil', 'sier feilaktig tilskrives det', 'feil er tilskrevet', 'Sitater tildelt', 'misattributed.', 'feilaktig tilskrives det', 'feil tilkoblet', 'feilaktig tilskrives', 'kontroversiell', 'er feil tildelt', 'feilaktig tildelt', 'krediteres feil', 'tvilsom', 'feilbehandlet', 'dårlig', 'feil', 'feil kreditert', 'unverified.', 'feil festet', 'feil kreditert', 'stemmer ikke', 'er tilskrevet feilaktig', 'mistenkelig'],\
    'ro': ['slab', 'contestată', 'incorect', 'spunând atribuit greșit', 'este atribuit în mod greșit', 'Citate atribuite', 'misattribuit', 'incorect atribuită', 'incorect conectat', 'incorect atribuită', 'controversat', 'este atribuită incorect', 'incorect atribuite', 'creditat incorect', 'îndoielnic', 'maltratat', 'slab', 'gresit', 'creditat greșit', 'neveriectificat', 'În mod incorect atașat', 'incorect creditate', 'incorect', 'este atribuită în mod eronat', 'suspicios'],\
    'ru': ['слабый', 'оспариваемый', 'неправильно', 'говорить неправильно приписанным', 'неправильно объясняется', 'цитаты назначены', 'несущественно', 'неправильно приписан', 'неправильно подключен', 'неправильно приписан', 'спорный', 'неверно назначен', 'неверно назначен', 'зачислен неправильно', 'сомнительный', 'плохо обращаться', 'плохо', 'неправильный', 'неправильно приписывать', 'неверно', 'неправильно прилагается', 'неправильно зачислено', 'неверный', 'приписывается по ошибке', 'подозрительный'],\
    'sk': ['slabý', 'sporný', 'nesprávne', 'hovorí nesprávne pripisované', 'nesprávne sa pripisuje', 'Pridelené citácie', 'nesprávny', 'Nesprávne pripísané', 'Nesprávne pripojené', 'nesprávne pripísané', 'kontroverzný', 'je nesprávne priradený', 'Nesprávne priradené', 'nesprávne pripísané', 'pochybný', 'nespokojný', 'úboho', 'vhodný', 'nesprávne pripísané', 'neoverený', 'Nesprávne pripojené', 'Nesprávne pripísané', 'nesprávny', 'sa pripisuje mylne', 'podozrivý'],\
    "sl": ["neozdrojované"'napačno prijavljeno', 'rekel napačno pripisano', 'napačno nakazana', 'napačno povezan', 'slabo', 'sumljivega', 'nepravilno dodeljena', 'neosgejavan.', 'dodeljeni citati', 'sporno', 'nepravilno pritrjena', 'nepreverjeno', 'napačno', 'je nepravilno dodeljen', 'nepravilno', 'napačno pripisano', 'se pripisuje pomotoma', 'in pavipe.', 'napačno pripisuje', 'dvomljiv', 'šibko', 'narobe', 'nepravilno pripisana'],\
    "sq": ['i diskutueshëm', 'atribuohet gabimisht', 'i keqtrajtuar', 'i atribuohet gabimisht', 'i pasaktë', 'kredituar gabimisht', 'caktohet gabimisht', 'i lidhur gabimisht', 'i dyshimtë', 'i pavepi', 'i gabuar', 'thënie të atribuara gabimisht', 'bashkangjitur gabimisht', 'dobet'],\
    "pl": ['zło', 'błędny', 'misattriruted.', 'źle traktować', 'słabo', 'wątpliwy', 'nieprawidłowo przymocowany', 'nieprawidłowo przypisany do', 'niepoprawnie przypisany', 'niepoprawnie połączony', 'mówiąc błędnie przypisany', 'kwestionować', 'cytaty przypisywane', 'niesprawdzony', 'błędnie przypisany', 'nieprawidłowo przypisany'], \
    'pt': ['fraca', 'contestada', 'incorretamente', 'dizendo atribuída incorretamente', 'atribuída incorretamente a', 'citações atribuídas', 'atribuída incorretamente', 'atribuída incorretamente', 'conectada incorretamente', ' atribuído incorretamente a ',' controverso ',' atribuído incorretamente ',' atribuído incorretamente ',' creditado incorretamente ',' duvidoso ',' maltratado ',' mal ',' errado ',' creditado incorretamente ',' não verificado ', 'incorretamente anexado', 'incorretamente creditado', 'incorreto', 'atribuído a incorretamente', 'suspeito'], \
    'ta': ['பலவீனமான', 'விவாதத்திற்குரியது', 'தவறாக', 'தவறாக சொல்லப்பட்டது', 'தவறாக காரணம்', 'மேற்கோள் ஒதுக்கப்படும்', 'misattributed.', 'தவறாக காரணம்', 'தவறாக இணைக்கப்பட்டுள்ளது', 'தவறாக காரணம்', 'சர்ச்சைக்குரிய', 'தவறாக ஒதுக்கப்பட்டுள்ளது', 'தவறாக ஒதுக்கப்படும்', 'தவறாக வழங்கப்பட்டது', 'சந்தேகம்', 'தவறாக நடத்தப்பட்டது', 'மோசமாக', 'தவறு', 'தவறாக வரவு', 'சரிபார்க்கப்படவில்லை', 'தவறாக இணைக்கப்பட்டுள்ளது', 'தவறாக நம்பப்படுகிறது', 'தவறானது', 'தவறுதலாக காரணம்', 'சந்தேகத்திற்கிடமான'],\
    'te': ['బలహీనమైన', 'వివాదాస్పదంగా', 'తప్పుగా', 'తప్పుగా ఆపాదించబడినది', 'తప్పుగా ఆపాదించబడినది', 'కేటాయించిన కోట్స్', 'myatattributed', 'తప్పుగా ఆపాదించబడినది', 'తప్పుగా కనెక్ట్ చేయబడింది', 'తప్పుగా ఆపాదించబడినది', 'వివాదాస్పద', 'తప్పుగా కేటాయించబడుతుంది', 'తప్పుగా కేటాయించబడింది', 'తప్పుగా జమ చేయబడుతుంది', 'అనుమానాస్పద', 'బాధితుడు', 'పేలవంగా', 'తప్పు', 'తప్పుగా ఘనత పొందింది', 'ధృవీకరించనిది', 'తప్పుగా జతచేయబడింది', 'తప్పుగా ఘనత పొందింది', 'తప్పు', 'తప్పుగా ఆపాదించబడింది', 'అనుమానాస్పద'],\
    'uk': ['слабкий', 'спірний', 'неправильно', 'кажучи неправильно віднесено', 'неправильно пояснюється', 'Призначені цитати', 'мізерний', 'неправильно віднесено', 'неправильно підключено', 'неправильно віднесено', 'суперечливий', 'неправильно призначено', 'неправильно призначено', 'неправильно приписується', 'сумнівний', 'погано', 'погано', 'неправильний', 'неправильно зарахований', 'неперевірений', 'неправильно прикріплені', 'неправильно зараховано', 'неправильний', 'пояснюється помилково', 'підозрілий'],\
    'ur': ['کمزور', 'متنازعہ', 'غلط طور پر', 'غلط طور پر منسوب کیا گیا ہے', 'غلط طور پر منسوب کیا جاتا ہے', 'حوالہ جات', 'غلط استعمال کی اطلاع دیتے ہوئے ایرر آ گیا ہے', 'غلط طور پر منسوب', 'غلط طور پر منسلک', 'غلط طور پر منسوب', 'متضاد', 'غلط طور پر تفویض کیا جاتا ہے', 'غلط طور پر تفویض', 'غلط طریقے سے کریڈٹ', 'شکست', 'غلطی', 'غریب', 'غلط', 'غلط طور پر کریڈٹ', 'غیر تصدیق شدہ', 'غلط طریقے سے منسلک', 'غلط طریقے سے کریڈٹ', 'غلط', 'غلطی سے منسوب کیا جاتا ہے', 'مشکوک'],\
    'vi': ['Yếu', 'tranh chấp', 'không chính xác', 'nói sai quy kết', 'sai được quy cho', 'Báo giá được giao', 'sai lệch', 'quy cho không chính xác', 'kết nối không chính xác', 'quy cho không chính xác cho.', 'gây tranh cãi', 'được giao không chính xác', 'chỉ định không chính xác', 'ghi có không chính xác', 'nghi ngờ', 'ngược đãi', 'kém', 'Sai lầm', 'Tín dụng sai', 'chưa được xác minh', 'đính kèm không chính xác', 'Credited không chính xác', 'không đúng', 'được quy cho nhầm', 'khả nghi'],\
    'zh': ['弱', '有争议', '不正确', '错误归因', '错误归因于', '引用分配', '错误归因', '错误归因', '错误连接', ' 错误地归因于', '有争议的', '被错误地分配', '错误地分配','记入错误','可疑','虐待','差','错误','错误记入','未验证', '错误附加','错误记入','错误','归因于错误','可疑']
}
#attributed? Neověřené disputed
# to be checked: Djela, Obras, Povedali o
forbidden_by_language  = {   
    "ar" : ["قالوا عنه","قالوا عنه","أشهر مؤلفاتها","الوصلات الخارجية"],\
    "az" : ["İstinadlar","Mənbə","Xarici keçidlər","Haqqında deyilənlər","istinadlar"],\
    "be":["Выказванні пра", "зноскі","спасылкі"],\
    "bg":["За нея","за него","Източници","Бележки","Външни препратки","литература"],\
    "bs":["Drugi o njemu","Djela","Također pogledajte","Vanjski linkovi","Izdanja"],\
    "ca":["citacions sobre","Referències","Bibliografia","Enllaços externs","referències"],\
    "co":["daveoù"],\
    "cs":["ve výrocích","Reference","Externí odkazy","Související"],\
    "da":["Eksterne henvisninger","Kilder"],\
    "de":["zitate mit bezug auf", ],\
    "el":["εξωτερικοί σύνδεσμοι"],\
    "es":["sobre", "Obras", "Véase también", "Bibliografía","referencias"],\
    "et":["välislingid"],\
    "en":["quotes about", "filmography", "footnote", "sources", "resources", "other projects","external links","links",\
         "notes", "note", "weblinks", "bibliogprahy", "related items","works", "references","literature","see","see also",\
             "footnote","other projects"],\
    "eu":["Kanpo loturak","Erreferentziak"],\
    "fa":["دربارهٔ او","پیوند به بیرون","جستارهای وابسته","منبع‌دار", "منابع","پیوند به‌بیرون"],\
    "fi":["sanottua","lähteet"],\
    "fr":["sur "],\
    "he":["על עצמה", "נאמר עליה","מקורות","קישורים חיצוניים","נאמר עליו","ראו גם"],\
    "hi":["बाहरी कडियाँ"],\
    "hr":["vanjske poveznice"],\
    "hu":["róla mondták","külső hivatkozások","Művei"],\
    "hy":["Աղբյուրներ","Ծանոթագրություններ","ծանոթագրություններ"],\
    "is":["tenglar"],\
    "id":["pranala luar"],\
    "it":["citazioni su","Doppiaggio","film","filmografia","altri progetti","voci correlate"], \
    "ja":["外部リンク"],\
    "ka":["რესურსები ინტერნეტში"],\
    "ko":["각주","관련 어록"],\
    "lt":["nuorodos"],\
    "nl":["over "], \
    "no":["eksterne lenker","referanser"],\
    "pl":["zobacz też","o "],\
    "pt":["obras", "sobre"],\
    "ro":["legături externe","despre"],\
    "ru":["Об","Фильмография","примечания","ссылки", "см. также"],\
    "sk":["Povedali o","iné projekty","referencie"],\
    "sl":["viri","sklici"],\
    "sq":["Thënie për të","Referimet","Shiko edhe","lidhje të jashtme","referime"],\
    "ta":["வெளி இணைப்புகள்","சான்றுகள்"],\
    "te":["మూలాలు"],\
    "tr":["Hakkında","kaynakça"],\
    "uk":["Про","Джерела","примітки","література"],\
    "ur":["حوالہ جات"],\
    "vi":["Liên kết ngoài","notennoù"],\
    "zh":["外部链接","参见","参考文献"]
    }

forbidden_by_language["ar"] = ["قالوا عنه", "قالوا عنه", "أشهر مؤلفاتها", "الوصلات الخارجية", "انظر أيضا إلى", "فهرس", "ويعمل", "ملحوظة", "المرجعي", "آخر حول هذا الموضوع", "في الذكرى", "قالوا عن ذلك", "فيلموجرافيا.", "قوله", "روابط", "قالوا عنه", "يقال عن", "يقتبس", "رابط ل", "الإحالات", "الأكثر شهرة الكتب", "الفمود الخارجي", "وصلات خارجية", "مصادر:", "عنه", "استفسارات الاعتماد", "المرجعي", "دبلجة", "فيلموجرافيا.", "له", "في", "روابط خارجية", "يلعب", "هامش", "قيل عنه", "ويعمل", "يلعب", "على", "مشاريع أخرى", "عن", "عنها", "موارد", "رابط خارجي", "المراجع", "مصادر", "قيل عنها", "الحواشي", "المراجع الخارجية", "الأصناف ذات الصلة", "مصدر", "ملحوظات:", "روابط", "لها", "إطلاق", "الشهادات - التوصيات", "ملحوظات", "قل", "الموارد في الإنترنت", "أنظر أيضا", "daveoù.", "رابط إلى الخارج", "عنه", "أنظر أيضا", "فيلم", "تشغيل", "مراجع", "قالوا O.", "متعلق ب", "رابط خارجي", "بيانات حول", "حول", "الاستشهادات المذكورة أعلاه", "مصادر", "سفير", "يقال له", "المؤلفات", "حول نفسها", "روابط خارجية", "التطبيقات ذات الصلة", "ونقلت فيما يتعلق", "ارى", "على", "الروابط الزائدة", "ونقلت حول", "فيلموجرافيا.", "هامش", "مصادر", "مصادر", "مشاريع أخرى", "روابط خارجية", "روابط", "ملحوظات", "ملاحظة", "روابط انترنت", "فهرس", "الأصناف ذات الصلة", "ويعمل", "المراجع", "المؤلفات", "ارى", "أنظر أيضا", "هامش", "مشاريع أخرى"]
forbidden_by_language["az"] = ["İstinadlar", "Mənbə", "Xarici keçidlər", "Haqqında deyilənlər", "istinadlar", "Də baxmaq", "Biblioqrafiya", "əsər", "Əlamətdar", "istinad", "Bu barədə başqa bir şey", "Yubileydə", "Bu barədə dedilər", "Filmoqrafiya", "Deyən", "linklər", "Onun haqqında dedilər", "Haqqında deyilir", "sitat gətirən", "Birləşdirmək", "refertral", "Ən məşhur kitablar", "Xarici TADS", "Xarici əlaqələr", "Mənbələr:", "onun haqqında", "sualları asılı idi", "İstinad", "Dublying", "filmoqrafiya", "onun üçün", "O", "xarici linklər", "pyes", "izdihamlı", "Onun haqqında deyildi", "Əsər", "Pyes", "üstünə", "Digər layihələr", "Haqqında", "onun haqqında", "Resurslar", "Xarici əlaqə", "arayışlar", "Mənbələr", "Onun haqqında deyildi", "izahat", "Xarici İstinadlar", "Oxşar əşyalar", "Mənbəyi", "Qeydlər:", "Linklər", "Onun üçün", "Buraxılış", "Şöhrətli", "Qeydlər", "ərz etmək", "İnternetdəki mənbələr", "Həmçinin bax", "daveoùù", "Xarici ilə əlaqə", "Onun haqqında", "həmçinin bax", "filmə", "yan", "Arayışlar", "Dedilər.", "Bahalı", "xarici əlaqə", "Haqqında ifadələr", "haqqında", "Yuxarıdakı sitatlar", "mənbələr", "Səfir", "Ona deyilir", "ədəbiyyat", "haqqında özü haqqında", "xarici linklər", "Əlaqədar tətbiqlər", "Hörmətlə sitatlar", "Görmək", "artıq", "Həddindən artıq bağlantılar", "haqqında sitatlar", "filmoqrafiya", "izdihamlı", "mənbələr", "resurslar", "Digər layihələr", "xarici linklər", "linklər", "qeydlər", "Qeyd", "vaklar", "biblioqrafiya", "Oxşar əşyalar", "əsər", "arayışlar", "ədəbiyyat", "görmək", "həmçinin bax", "izdihamlı", "Digər layihələr"]
forbidden_by_language["be"] = ["Выказванні пра", "зноскі", "спасылкі", "Таксама глядзець на", "Бібліяграфія", "работы", "нотенно", "спасылка", "Іншы пра гэта", "У гадавіне", "Яны сказалі пра гэта", "Фільмаграфія", "Кажучы", "спасылкі", "Яны сказалі пра яго", "Кажуць пра", "каціроўкі", "Спасылка на", "рэфералы", "Самыя вядомыя кнігі", "Знешнія казалі", "Знешнія злучэння", "Крыніцы:", "пра яго", "Залежныя запыты", "Спасылка", "Нядбайнны", "фільмаграфія", "для яго", "Аб", "Знешнія спасылкі", "п'есы", "знос", "было сказана пра яго", "Работы", "П'есы", "на", "Іншыя праекты", "Пра", "пра яе", "Рэсурсы", "Знешняя спасылка", "рэкамендацыі", "Крыніцы", "Было сказана пра яе", "знос", "Знешнія спасылкі", "Звязаныя элементы", "Крыніца", "Нататкі:", "Спасылкі", "Для яе", "Верхі", "Водгукі", "Нататкі", "гаварыць", "Рэсурсы ў Інтэрнэце", "См таксама", "Спасылка на вонкавым боку", "Пра яго", "см таксама", "плёнка", "на", "Рэкамендацыі", "Яны сказалі, што О.", "Звязаны", "знешняя спасылка", "Заявы аб", "пра", "Цытаты вышэй", "крыніцы", "літаратура", "знешнія спасылкі", "Звязаныя з прыкладаннямі", "Каціроўкі ў адносінах да", "Бачыць", "больш", "Лішак спасылкі", "цытаты аб", "фільмаграфія", "крыніцы", "рэсурсы", "іншыя праекты", "знешнія спасылкі", "спасылкі", "нататкі", "нататка", "weblinks", "бібліяграфія", "Звязаныя элементы", "работы", "рэкамендацыі", "літаратура", "бачыць", "см таксама", "іншыя праекты"]
forbidden_by_language["bg"] = ["За нея", "за него", "Източници", "Бележки", "Външни препратки", "литература", "Също погледнете", "Библиография", "върши работа", "Бележит", "справка", "Друг за него", "в годишнината", "Те казаха за това", "Филмография", "Да се каже", "Връзки", "Те казаха за него", "Се казва", "Връзка към", "Реферали", "Най-известните книги", "Външни тади", "Външни връзки", "Източници:", "за него", "Запитвания", "Справка", "Дублиране", "Филмография", "за него", "О", "външни връзки", "Играе", "Бележка под линия", "Беше казано за него", "Върши работа", "Играе", "в", "Други проекти", "относно", "за нея", "Ресурси", "Външен линк", "препратки", "Източници", "Беше казано за нея", "Бележки под линия", "Външни препратки", "Подобни продукти", "Източник", "Забележки:", "Връзки", "За нея", "Освобождаване", "Отзиви", "Бележки", "казвам", "Ресурси в Интернет", "Вижте също", "Дъстина", "Връзка с външната страна", "За него", "Вижте също", "филм", "На", "Препратки", "Те казаха О.", "Свързани", "външен линк", "Изявления за", "относно", "Цитати над", "Източници", "Посланик", "Му се казва", "Литература", "за себе си", "външни връзки", "Свързани приложения", "Цитати по отношение на", "Вж", "над", "Излишните връзки", "цитати за", "Филмография", "Бележка под линия", "Източници", "Ресурси", "Други проекти", "външни връзки", "Връзки", "Бележки", "Забележка", "WeBlinks.", "Библиография", "подобни продукти", "върши работа", "препратки", "Литература", "вж", "Вижте също", "Бележка под линия", "Други проекти"]
forbidden_by_language["bs"] = ["Drugi o njemu", "Djela", "Također pogledajte", "Vanjski linkovi", "Izdanja", "Takođe pogledajte", "Bibliografija", "radovi", "Primijetan", "referenca", "Još jedan o tome", "u godišnjici", "Rekli su o tome", "Filmografija", "Govoreći", "linkove", "Rekli su o njemu", "Su rekli o", "citati", "Link na", "preporuke", "Najpoznatije knjige", "Vanjski tads", "Vanjske veze", "Izvori:", "o njemu", "Zavito upiti", "Referenca", "Presnimav", "Filmografija", "za njega", "O", "Vanjske veze", "igra", "fusnota", "Rečeno je o njemu", "Radovi", "Igra", "na", "Ostali projekti", "O", "o njoj", "Resursi", "Vanjska veza", "reference", "Izvori", "Rečeno je o njoj", "fusnote", "Vanjske reference", "Srodni predmeti", "Izvor", "Napomene:", "Linkove", "Za nju", "Izdanja", "Testimonials", "Bilješke", "izgovoriti", "Resursi na Internetu", "Vidjeti i", "Daveoù", "Veza sa spolja", "O njemu", "vidjeti i", "film", "na", "Reference", "Rekli su O.", "Povezani", "Vanjska veza", "Izjave o", "o", "Citati gore", "izvori", "Ambasador", "Kaže mu", "literatura", "o sebi", "Vanjske veze", "Srodne aplikacije", "Citati u odnosu na", "Vidjeti", "preko", "Višak veze", "citati o", "Filmografija", "fusnota", "izvori", "resursi", "Ostali projekti", "Vanjske veze", "linkove", "bilješke", "Bilješka", "Webliks", "bibliografija", "Srodni predmeti", "radovi", "reference", "literatura", "vidjeti", "vidjeti i", "fusnota", "Ostali projekti"]
forbidden_by_language["ca"] = ["citacions sobre", "Referències", "Bibliografia", "Enllaços externs", "referències", "També mireu", "Bibliografia", "treballa", "Notable", "referència", "Un altre sobre això", "En l'aniversari", "Van dir sobre això", "Filtrografia", "Dient", "enllaç", "Van dir sobre ell", "Es diu sobre", "cites", "Enllaç a", "referències", "Els llibres més famosos", "Tads exteriors", "Connexions externes", "Fonts:", "sobre ell", "Consultes dependents", "Referència", "% De comportament", "filtrografia", "per ell", "O a", "Enllaços externs", "obert", "Nota al peu", "Es va dir sobre ell", "Treballa", "Obert", "a sobre de", "Altres projectes", "Sobre", "sobre ella", "Recursos", "Enllaç extern", "referències", "Fonts", "Es va dir sobre ella", "Notes al peu de pàgina", "Referències externes", "Articles relacionats", "Font", "NOTES:", "Enllaç", "Per ella", "Llançaments", "Testimonis", "Notes", "dir", "Recursos a Internet", "Vegeu també", "daveoù", "Enllaç a l'exterior", "Sobre ell", "Vegeu també", "pel·lícula", "conectada", "Referències", "Van dir O.", "Relacionada", "Enllaç extern", "Declaracions sobre", "Sobre", "Cites anteriors", "fonts", "Ambaixador", "Se li diu", "literatura", "sobre ella mateixa", "Enllaços externs", "Aplicacions relacionades", "Cites respecte a", "Veure", "sobrar", "Enllaços d'excés", "cites sobre", "filtrografia", "Nota al peu", "fonts", "recursos", "Altres projectes", "Enllaços externs", "enllaç", "notes", "nota", "Weblinks", "bibliografia", "Articles relacionats", "treballa", "referències", "literatura", "veure", "Vegeu també", "Nota al peu", "Altres projectes"]
forbidden_by_language["co"] = ["daveoù", "Fighjà ancu", "Bibliografia", "FUNZIONI", "Notabile", "Riferimentu", "Un altru nantu à questu", "In l'anniversariu", "Anu dettu di questu", "Filmografia", "Dicendu à", "Ligami", "Anu dettu di ellu", "Sò dettu di circa", "Ligame cù", "I referenze", "I libri più famosi", "Tadri esterni", "Cunnessioni esterni", "FONTI:", "circa ellu", "Quistioni dipendenti", "Riferimentu", "Dubaghju", "Filmografia", "per ellu", "O", "Ligami esterni", "Ghjucà", "nota di nota", "si dicia di ellu", "FUNZIONI", "Ghjucà", "à", "Altri prughjetti", "Circa à", "circa ella", "Risorse", "Link esternu", "Riferimenti", "Fonti", "Si dicia di ella", "Testrootes", "Riferimenti esterni", "Oggetti Relativi", "Fonte", "NOTI:", "Ligami", "Per ella", "Release", "Testimonianza", "Note", "dì", "Risorse in Internet", "Vede ancu", "daveoù", "Ligame à l'esterno", "Circa ellu", "vede ancu", "film", "avanti", "Riferimenti", "Anu dettu O.", "Ligatu", "Link esternu", "Dichjarazioni circa", "circa à", "Citazioni sopra", "fonti", "Ambasciatore", "Si dice à ellu", "Letteratura", "circa ella stessu", "ligami esterni", "Applicazioni ligate", "Quotes cun rispettu à", "Vede", "finitu", "Ligami d'uccasioni", "citazioni circa", "Filmografia", "nota di nota", "fonti", "Risorse", "altri prughjetti", "ligami esterni", "Ligami", "Note", "Nota", "weblinks", "bibliografia", "Oggetti Relativi", "FUNZIONI", "Riferimenti", "Letteratura", "vede", "vede ancu", "nota di nota", "altri prughjetti"] 
forbidden_by_language["cs"] = ["ve výrocích", "Reference", "Externí odkazy", "Související", "Také se podívejte na", "Bibliografie", "práce", "Pozoruhodný", "odkaz", "Další o tom", "v výročí", "Řekli o tom", "Filmografie", "Říkat", "Odkazy", "Řekli o něm", "Říkají se asi", "citáty", "Odkaz na", "odkazy", "Nejznámější knihy", "Vnější Tads.", "Externí připojení", "Prameny:", "o něm", "Závislé dotazy", "Odkaz", "Dabing", "filmografie", "pro něj", "Ó", "externí odkazy", "hra", "poznámka pod čarou", "Řekl to o něm", "Práce", "Hra", "na", "Další projekty", "O", "o ní", "Zdroje", "Externí odkaz", "Reference", "Prameny", "Řekl to o ní", "poznámky pod čarou", "Externí odkazy", "Související zboží", "Zdroj", "Poznámky:", "Odkazy", "Pro ni", "Releases", "Svědectví", "Poznámky", "říci", "Zdroje v Internetu", "Viz také", "daveoù.", "Odkaz na vnější stranu", "O něm", "viz také", "film", "na", "Reference", "Řekli O.", "Příbuzný", "Externí odkaz", "Výkazy", "o", "Citace výše", "prameny", "Velvyslanec", "Říká se mu", "literatura", "o sobě", "externí odkazy", "Související aplikace", "S ohledem na", "Vidět", "přes", "Přebytečné odkazy", "cituje", "filmografie", "poznámka pod čarou", "prameny", "zdroje", "Další projekty", "externí odkazy", "Odkazy", "poznámky", "Poznámka", "webové odkazy", "bibliografie", "Související zboží", "práce", "Reference", "literatura", "vidět", "viz také", "poznámka pod čarou", "Další projekty"]
forbidden_by_language["da"] = ["Eksterne henvisninger", "Kilder", "Se også på", "Bibliografi.", "arbejder", "Bemærkelsesværdig", "reference", "En anden om det", "i jubilæet.", "de sagde om det", "Filmografi.", "Siger til", "links.", "De sagde om ham", "Er sagt omkring", "citater", "Link til", "henvisninger.", "De mest berømte bøger", "Ydre tads.", "Eksterne forbindelser", "Kilder:", "om ham", "Afhængige forespørgsler", "Reference", "Dubbing.", "Filmografi.", "For ham", "O.", "eksterne links", "spiller.", "fodnote.", "Det blev sagt om ham", "Arbejder", "Spiller.", "på", "Andre projekter", "Om", "om hende", "Ressourcer.", "Eksternt link", "Referencer.", "Kilder.", "Det blev sagt om hende", "fodnoter.", "Eksterne referencer.", "Relaterede elementer.", "Kilde", "Noter:", "Links.", "For hende", "Udgivelser.", "Testimonials.", "Noter.", "sige", "Ressourcer på internettet", "Se også", "daveoù.", "Link til ydersiden", "Om ham", "se også", "film", "på", "Referencer.", "De sagde O.", "Relaterede", "Eksternt link", "Udsagn om", "om", "Citater ovenfor", "Kilder.", "Ambassadør", "Det siges til ham", "litteratur", "om sig selv.", "eksterne links", "Relaterede applikationer", "Citater med hensyn til", "Se", "over", "Overskydende links.", "citater om", "Filmografi.", "fodnote.", "Kilder.", "ressourcer.", "andre projekter", "eksterne links", "links.", "noter.", "Bemærk", "Weblinks.", "bibliografi", "relaterede elementer.", "arbejder", "Referencer.", "litteratur", "se", "se også", "fodnote.", "andre projekter"]
forbidden_by_language["de"] = ["Zitate über", "Filmografie", "Fußnote", "Quellen", "Ressourcen", "andere Projekte", "externe Links", "Links", "Notizen", "Hinweis", "Weblinks", "Literaturverzeichnis", "verwandte Artikel", "Werke", "Referenzen", "Literatur", "sehen", "siehe auch", "Fußnote", "andere Projekte", "Auch anschauen", "Bibliographie", "Werke", "Bemerkenswert", "Referenz", "Noch einer darüber", "im Jubiläum", "Sie sagten darüber", "Filmografie", "Sagen zu", "Links", "Sie sagten über ihn", "Sind sagte über", "Zitate", "Link zu", "Empfehlungen", "Die berühmtesten Bücher", "Outer tads", "Externe Verbindungen", "Quellen:", "über ihn", "Abhängige Anfragen", " Referenz", "Synchronisation", "Filmografie", "für ihn", "O", "Externe Links", "Spiele", "Fußnote", "es wurde über ihn gesagt", "Werke", "Spiele", " auf", "Andere Projekte", "Über", "Über sie", "Ressourcen", "Externer Link", "Referenzen", "Quellen", "Es wurde über sie gesagt", "Fußnoten", "Externe Verweise", "Verwandte Artikel", "Quelle", "Notizen:", "Links", "Für sie", "Veröffentlichungen", "Testimonials", "Nicht es", "sagen", "Ressourcen im Internet", "Siehe auch", "daveoù", "Link nach außen", "Über ihn", "Siehe auch", "Film", "on", "Referenzen", "Sie sagten O.", "Verwandte", "externer Link", "Aussagen über", "über", "Zitate oben", "Quellen", "Botschafter", "Es wird ihm gesagt", "Literatur", "über sich selbst", "externe Links", "Verwandte Anwendungen", "Zitate in Bezug auf", "Siehe", "über", "Überzählige Links", "Zitate über", "Filmografie", "Fußnote", " Quellen", "Ressourcen", "andere Projekte", "externe Links", "Links", "Notizen", "Hinweis", "Weblinks", "Bibliographie", "Verwandte Artikel", "Werke", "Referenzen", "Literatur", "sehen", "siehe auch", "Fußnote", "andere Projekte"]
forbidden_by_language["el"] = ["εξωτερικοί σύνδεσμοι", "Επίσης κοιτάξτε", "Βιβλιογραφία", "έργα", "Αξιοσημείωτος", "αναφορά", "Ένα άλλο για αυτό", "Στην επέτειο", "είπαν γι 'αυτό", "Φωτοτυπογραφία", "Λέγοντας", "συνδέσεις", "Είπαν γι 'αυτόν", "Λέγονται", "αποσπάσματα", "Συνδέω με", "παραπομπές", "Τα πιο διάσημα βιβλία", "Εξωτερικά μαύρα", "Εξωτερικές συνδέσεις", "Πηγές:", "για αυτόν", "εξαρτώμενα ερωτήματα", "Αναφορά", "Μεταγλώ", "φωτοτυπογραφία", "για εκείνον", "O", "εξωτερικοί σύνδεσμοι", "παίζει", "υποσημείωση", "Είχε ειπωθεί γι 'αυτόν", "Εργα", "Παίζει", "επάνω σε", "Άλλα έργα", "Σχετικά με", "σχετικά με αυτήν", "Πόροι", "Εξωτερικός σύνδεσμος", "βιβλιογραφικές αναφορές", "Πηγές", "Είχε ειπωθεί γι 'αυτήν", "υποσημειώσεις", "Εξωτερικές αναφορές", "Σχετικά Αντικείμενα", "Πηγή", "Σημειώσεις:", "Συνδέσεις", "Για εκείνη", "Απελευθερώνει", "Μαρτυρίες", "Σημειώνει", "λένε", "Πόροι στο Διαδίκτυο", "Δείτε επίσης", "daveoù", "Σύνδεσμος προς το εξωτερικό", "Για αυτόν", "δείτε επίσης", "ταινία", "επί", "βιβλιογραφικές αναφορές", "Είπαν Ο.", "Σχετίζεται με", "εξωτερικός σύνδεσμος", "Δηλώσεις σχετικά με", "σχετικά με", "Παραπάνω αναφορές", "πηγές", "Πρεσβευτής", "Του λέγεται", "λογοτεχνία", "Σχετικά με τον εαυτό της", "εξωτερικοί σύνδεσμοι", "Σχετικές εφαρμογές", "Αποσπάσματα σε σχέση με", "Βλέπω", "πάνω από", "Υπερβολικοί σύνδεσμοι", "αποσπάσματα περίπου", "φωτοτυπογραφία", "υποσημείωση", "πηγές", "πόροι", "Άλλα έργα", "εξωτερικοί σύνδεσμοι", "συνδέσεις", "σημειώνει", "Σημείωση", "διαδικτυακοί σύνδεσμοι", "βιβλιογραφία", "Σχετικά Αντικείμενα", "έργα", "βιβλιογραφικές αναφορές", "λογοτεχνία", "βλέπω", "δείτε επίσης", "υποσημείωση", "Άλλα έργα"]
forbidden_by_language["et"] = ["välislingid", "Vaata ka", "Bibliograafia", "töötama", "Märkimisväärne", "viide", "Teine sellest", "aastapäeval", "Nad ütlesid sellest", "Filmograafia", "Öeldes", "lingid", "Nad ütlesid temast", "Öeldakse", "tsitaat", "Link", "viited", "Kõige kuulsamad raamatud", "Outer Tads", "Välised ühendused", "Allikad:", "temast", "sõltus päringutest", "Viide", "Dubleerimine", "filmograafia", "tema jaoks", "O", "Välised lingid", "mängima", "joonealune märkus", "Ta ütles temast", "Töötama", "Mängima", "peale", "Muud projektid", "Umbes", "temast", "Vahendid", "Väline link", "viited", "Allikad", "Tema kohta öeldi", "joonealused märkused", "Välised viited", "Seotud üksused", "Allikas", "Märkused:", "Lingid", "Temale", "Väljaanded", "Iseloomustused", "Märgib", "ütlema", "Ressursid Internetis", "Vaata ka", "daveoù", "Link väljastpoolt", "Temast", "Vaata ka", "film", "peal", "Viited", "Nad ütlesid O.", "Seotud", "Väline link", "Avaldused", "umbes", "Valitud tsitaadid", "allikad", "Suursaadik", "See on talle öeldud", "kirjandus", "ennast", "Välised lingid", "Seotud rakendused", "Hinnapakkumisi", "Nägema", "üle", "Liigne lingid", "hinnapakkumisi", "filmograafia", "joonealune märkus", "allikad", "vahendid", "Muud projektid", "Välised lingid", "lingid", "märgib", "Märge", "weblinks", "bibliograafia", "Seotud üksused", "töötama", "viited", "kirjandus", "nägema", "Vaata ka", "joonealune märkus", "Muud projektid"]
forbidden_by_language["en"] = ["quotes about", "filmography", "footnote", "sources", "resources", "other projects", "external links", "links", "notes", "note", "weblinks", "bibliography", "related items", "works", "references", "literature", "see", "see also", "footnote", "other projects", "Also look at", "Bibliography", "works", "Notable", "reference", "Another about it", "in the anniversary", "they said about it", "Filmography", "Saying to", "links", "They said about him", "Are said about", "Link to", "referrals", "The most famous books", "Outer tads", "External connections", "Sources:", "about him", "depended queries", "Reference", "Dubbing", "filmography", "for him", "O", "External links", "plays", "footnote", "it was said about him", "Works", "Plays", "upon", "Other projects", "About", "about her", "Resources", "External link", "references", "Sources", "It was said about her", "footnotes", "External references", "Related items", "Source", "Notes:", "Links", "For her", "Releases", "Testimonials", "Notes", "say", "resources in Internet", "See also", "daveoù", "Link to the outside", "About him", "see also", "film", "on", "References", "They said O.", "Related", "external link", "Statements about", "about", "Citations above", "sources", "Ambassador", "It is said to him", "literature", "about herself", "external links", "Related Applications", "Quotes with respect to", "See", "over", "Excess links", "quotes about", "filmography", "footnote", "sources", "resources", "other projects", "external links", "links", "notes", "note", "weblinks", "bibliography", "related items", "works", "references", "literature", "see", "see also", "footnote", "other projects"]
forbidden_by_language["eu"] = ["Kanpo loturak", "Erreferentziak", "Begira ere", "Bibliografia", "zeregin", "Nabarmen", "kontsulta", "Horri buruz", "Urteurrenean", "Esan zuten", "Filmografia", "Esanda", "estekak", "Berari buruz esan zuten", "Esaten da", "aipamen", "Esteka", "ikuskapen", "Liburu ospetsuenak", "Kanpoko Tads", "Kanpoko konexioak", "Iturriak:", "Berari buruz", "Dependatutako kontsultak", "Kontsulta", "Bosbing", "Filmografia", "harentzat", "O", "Kanpoko estekak", "Plays", "oharra", "Berari buruz esan zen", "Zeregin", "Plays", "-en gainean", "Beste proiektu batzuk", "Ei buruz", "haren inguruan", "Baliabide", "Kanpoko esteka", "erreferentziak", "Iturriak", "Berari buruz esan zen", "Oharrak", "Kanpoko erreferentziak", "Lotutako elementuak", "Iturri", "Oharrak:", "Estekak", "Berarentzat", "Oheratu", "Testigantzak", "Ohar", "esan", "Baliabideak Interneten", "Ikusi ere", "Daveoù", "Kanpotik estekatu", "Berari buruz", "ikusi ere", "mintz", "-en gainean", "Erreferentziak", "Esan zuten O.", "Lotinduta", "Kanpoko esteka", "Adierazpenak", "ei buruz", "Goiko aipuak", "iturriak", "Enbaxadore", "Esan dio", "literatura", "bere buruari buruz", "Kanpoko estekak", "Lotutako aplikazioak", "Aipamenak", "Ikusi", "-en gainetik", "Gehiegizko estekak", "aipamenak buruz", "Filmografia", "oharra", "iturriak", "baliabide", "Beste proiektu batzuk", "Kanpoko estekak", "estekak", "ohar", "ohar", "Weblinkak", "Bibliografia", "Lotutako elementuak", "zeregin", "erreferentziak", "literatura", "ikusi", "ikusi ere", "oharra", "Beste proiektu batzuk"]
forbidden_by_language["fa"] = ["دربارهٔ او", "پیوند به بیرون", "جستارهای وابسته", "منبع\u200cدار", "منابع", "پیوند به\u200cبیرون", "همچنین نگاه کن", "کتابشناسی - فهرست کتب", "آثار", "قابل توجه", "مرجع", "یکی دیگر در مورد آن", "در سالگرد", "آنها درباره آن گفتند", "فیلمنامه نویسی", "گفتن به", "پیوندها", "آنها درباره او گفتند", "در مورد آنها گفته شده است", "نقل قول", "پیوند به", "ارجاع", "مشهورترین کتاب ها", "بیرونی", "اتصالات خارجی", "منابع:", "درباره ی او", "پرسش های وابسته", "ارجاع", "دوبله", "فیلمنامه نویسی", "برای او", "o", "لینک های خارجی", "نمایشنامه", "پاورقی", "در مورد او گفته شد", "آثار", "نمایشنامه", "بر", "پروژه های دیگر", "در باره", "در مورد او", "منابع", "لینک خارجی", "منابع", "منابع", "در مورد او گفته شد", "پانویسها و منابع", "منابع خارجی", "آیتم های مرتبط", "منبع", "یادداشت:", "پیوندها", "برای او", "منتشر شده", "توصیفات", "یادداشت", "گفتن", "منابع در اینترنت", "همچنین ببینید", "daveoù", "پیوند به خارج", "درباره ی او", "همچنین ببینید", "فیلم", "بر", "منابع", "آنها گفتند O.", "مربوط", "لینک خارجی", "اظهارات در مورد", "در باره", "نقل قول بالا", "منابع", "سفیر", "به او گفته شده است", "ادبیات", "درباره خودش", "لینک های خارجی", "برنامه های مرتبط", "نقل قول با توجه به", "دیدن", "بر فراز", "لینک های اضافی", "نقل قول در مورد", "فیلمنامه نویسی", "پاورقی", "منابع", "منابع", "پروژه های دیگر", "لینک های خارجی", "پیوندها", "یادداشت", "توجه داشته باشید", "weblinks", "کتابشناسی - فهرست کتب", "آیتم های مرتبط", "آثار", "منابع", "ادبیات", "دیدن", "همچنین ببینید", "پاورقی", "پروژه های دیگر"]
forbidden_by_language["es"] = ["citas sobre", "filmografía", "nota al pie", "fuentes", "recursos", "otros proyectos", "enlaces externos", "enlaces", "notas", "nota", "enlaces web", "bibliografía"," artículos relacionados"," obras"," referencias"," literatura"," ver"," ver también"," nota al pie"," otros proyectos"," Mirar también"," Bibliografía"," obras", "Notable", "referencia", "Otro sobre eso", "en el aniversario", "Ellos dijeron al respecto", "Filmografía", "Diciendo a", "Enlaces", "Ellos dijeron sobre él", "Son dijo sobre"," citas"," Enlace a"," referencias"," Los libros más famosos"," Tads externos"," Conexiones externas"," Fuentes:"," sobre él"," consultas dependientes"," Referencia"," Doblaje"," filmografía"," para él"," O"," Enlaces externos"," obras de teatro"," nota al pie"," se dijo sobre él"," Obras"," Obras de teatro"," sobre"," Otros proyectos"," Acerca de"," Acerca de ella"," Recursos"," Enlace externo"," Referencias"," Fuentes"," Se dijo sobre ella"," Notas al pie"," Referencias externas", "Artículos relacionados", "Fuente", "Notas:", "Enlaces", "Para ella", "Lanzamientos", "Testimonios", "No es"," decir"," recursos en Internet"," Ver también"," daveoù"," Enlace con el exterior"," Acerca de él"," ver también"," película"," sobre"," Referencias", "Dijeron O.", "Relacionado", "Enlace externo", "Declaraciones sobre", "Sobre", "Citas arriba", "Fuentes", "Embajador", "Se le dice a él", "Literatura", "sobre ella", "enlaces externos", "Aplicaciones relacionadas", "Citas con respecto a", "Ver", "sobre", "Enlaces en exceso", "Citas sobre", "filmografía", "nota al pie", " fuentes"," recursos"," otros proyectos"," enlaces externos"," enlaces"," notas"," nota"," enlaces web"," bibliografía"," artículos relacionados"," obras"," referencias", "literatura", "ver", "ver también", "nota al pie", "otros proyectos"]
forbidden_by_language["fi"] = ["lainaukset aiheesta", "filmografia", "alaviite", "lähteet", "resurssit", "muut projektit", "ulkoiset linkit", "linkit", "muistiinpanot", "huomautus", "weblinks", "bibliografia", "liittyvät kohteet", "teokset", "viitteet", "kirjallisuus", "katso", "katso myös", "alaviite", "muut projektit", "katso myös", "Bibliografia", "teokset", "Huomattava", "viite", "Toinen siitä", "juhlapäivänä", "he sanoivat siitä", "Filmografia", "Sanominen", "linkit", "He sanoivat hänestä", "Ovatko sanoi aiheesta", "lainaukset", "Linkki", "viittaukset", "kuuluisimmat kirjat", "Ulkoiset", "Ulkoiset yhteydet", "Lähteet:", "Hänestä", "riippuvaiset kyselyt", " Viite", "Kopiointi", "filmografia", "hänelle", "O", "ulkoiset linkit", "näytelmät", "alaviite", "hänestä sanottiin", "teokset", "näytelmät", " upon", "Muut projektit", "Tietoja", "Hänestä", "Resurssit", "Ulkoinen linkki", "viitteet", "Lähteet", "Hänestä sanottiin", "alaviitteet", "Ulkoiset viitteet", "Aiheeseen liittyvät kohteet", "Lähde", "Huomautukset:", "Linkit", "Hänelle", "Julkaisut", "Lausunnot", "Ei es", "sano", "resurssit Internetissä", "Katso myös", "daveoù", "Linkki ulkopuolelta", "Tietoa hänestä", "katso myös", "elokuva", "päällä", "viitteet", "He sanoivat O.", "Aiheeseen liittyvä", "ulkoinen linkki", "Lausunnot aiheesta", "Tietoja", "Yllä olevat lainaukset", "lähteet", "suurlähettiläs", "Hänelle sanotaan", "kirjallisuus", "itsestään", "ulkoiset linkit", "Aiheeseen liittyvät sovellukset", "Lainaukset suhteessa", "Katso", "yli", "Ylimääräiset linkit", "lainauksia", "filmografia", "alaviite", " lähteet", "resurssit", "muut projektit", "ulkoiset linkit", "linkit", "muistiinpanot", "huomautus", "verkkolinkit", "bibliografia", "liittyvät kohteet", "teokset", "viitteet", "kirjallisuus", "katso", "katso myös", "alaviite", "muut hankkeet"] 
forbidden_by_language["fr"] = ["citations sur", "filmographie", "note de bas de page", "sources", "ressources", "autres projets", "liens externes", "liens", "notes", "note", "liens web", "bibliogprahie", "éléments liés", "œuvres", "références", "littérature", "voir", "voir aussi", "note de bas de page", "autres projets", "Regarder aussi", "Bibliographie", "œuvres", "Remarquable", "référence", "Un autre à ce sujet", "à l'anniversaire", "ils en ont dit", "Filmographie", "En disant à", "liens", "Ils ont dit à propos de lui", "Sont dit à propos de", "citations", "Lien vers", "références", "Les livres les plus célèbres", "Tads externes", "Connexions externes", "Sources :", "à propos de lui", "requêtes dépendantes", " Référence", "Doublage", "filmographie", "pour lui", "O", "Liens externes", "pièces", "note de bas de page", "on a dit de lui", "Travaux", "Joues", " sur", "Autres projets", "À propos", "à propos d'elle", "Ressources", "Lien externe", "Références", "Sources", "On a dit d'elle", "Notes de bas de page", "Références externes", "Articles associés", "Source", "Notes :", "Liens", "Pour elle", "Releases", "Témoignages", "Non es", "dire", "ressources sur Internet", "Voir aussi", "daveoù", "Lien vers l'extérieur", "A propos de lui", "voir aussi", "film", "sur", "Références", "Ils ont dit O.", "Connexe", "lien externe", "Déclarations sur", "à propos", "Citations ci-dessus", "sources", "Ambassadeur", "On lui dit", "littérature", "à propos d'elle-même", "liens externes", "Applications associées", "Citations concernant", "Voir", "over", "Liens excédentaires", "Citations sur", "filmographie", "note de bas de page", " sources", "ressources", "autres projets", "liens externes", "liens", "notes", "note", "liens web", "bibliographie", "éléments associés", "ouvrages", "références", "littérature", "voir", "voir aussi", "note de bas de page", "autres projets"]
forbidden_by_language["he"] = ["ציטוטים על", "פילמוגרפיה", "הערת שוליים", "מקורות", "משאבים", "פרויקטים אחרים", "קישורים חיצוניים", "קישורים", "הערות", "הערה", "קישורי אינטרנט", "ביבליוגפרה'", "פריטים קשורים", "עבודות", "הפניות", "ספרות", "ראה", "ראה גם", "הערת שוליים", "פרויקטים אחרים", "הסתכל גם על", "ביבליוגרפיה", "עבודות", "ראוי לציון", "התייחסות", "עוד על זה", "ביום השנה", "אמרו על זה", "פילמוגרפיה", "אומרים ל", "קישורים", "אמרו עליו", "האם אמר על", "ציטוטים", "קישור אל", "הפניות", "'הספרים המפורסמים ביותר", "תקשורים חיצוניים", "חיבורים חיצוניים", "מקורות:", "עליו", "שאילתות תלויות", " הפניה", "דיבוב", "פילמוגרפיה", "בשבילו", "O", "קישורים חיצוניים", "הצגות", "הערת שוליים", "אמרו עליו", "עבודות", "מחזות", " על", "פרויקטים אחרים", "אודות", "עליה", "משאבים", "קישור חיצוני", "הפניות", "מקורות", "נאמר עליה", "הערות שוליים", "הפניות חיצוניות", "פריטים קשורים", "מקור", "הערות:", "קישורים", "בשבילה", "פרסומים", "המלצות", "לא es", "אמר", "משאבים באינטרנט", "ראה גם", "daveoù", "קישור אל החוץ", "אודותיו", "ראה גם", "סרט", "על", "הפניות", "הם אמרו O", "קשורים", "קישור חיצוני", "הצהרות על", "על", "ציטוטים למעלה", "מקורות", "שגריר", "נאמר לו", "ספרות", "על עצמה", "קישורים חיצוניים", "יישומים קשורים", "ציטוטים ביחס ל", "ראה", "מעל", "קישורים עודפים", "ציטוטים על", "פילמוגרפיה", "הערת שוליים", " מקורות", "משאבים", "פרויקטים אחרים", "קישורים חיצוניים", "קישורים", "הערות", "הערה", "קישורי אינטרנט", "ביבליוגרפיה", "פריטים קשורים", "עבודות", "הפניות", "ספרות", "ראה", "ראה גם", "הערת שוליים", "פרויקטים אחרים"]
forbidden_by_language["hi"] = ["के बारे में उद्धरण", "फिल्मोग्राफी", "फुटनोट", "स्रोत", "संसाधन", "अन्य परियोजनाएं", "बाहरी लिंक", "लिंक", "नोट्स", "नोट", "वेबलिंक", "ग्रंथ सूची", "संबंधित आइटम", "कार्य", "संदर्भ", "साहित्य", "देखें", "यह भी देखें", "फुटनोट", "अन्य परियोजनाएं", "भी देखें", "ग्रंथ सूची", "काम करता है", "उल्लेखनीय", "संदर्भ", "इसके बारे में एक और", "वर्षगांठ में", "उन्होंने इसके बारे में कहा", "फिल्मोग्राफी", "सेइंग टू", "लिंक्स", "उन्होंने उसके बारे में कहा", "हैं के बारे में कहा", "उद्धरण", "लिंक टू", "रेफ़रल", "सबसे प्रसिद्ध किताबें", "बाहरी बच्चे", "बाहरी कनेक्शन", "स्रोत:", "उसके बारे में", "आश्रित प्रश्न", " संदर्भ", "डबिंग", "फिल्मोग्राफी", "उसके लिए", "ओ", "बाहरी लिंक", "नाटक", "फुटनोट", "उसके बारे में कहा गया", "काम करता है", "नाटक", " on", "अन्य प्रोजेक्ट", "अबाउट", "उसके बारे में", "संसाधन", "बाहरी लिंक", "संदर्भ", "स्रोत", "उसके बारे में कहा गया", "फुटनोट", "बाहरी संदर्भ", "संबंधित आइटम", "स्रोत", "नोट्स:", "लिंक", "उसके लिए", "रिलीज़", "प्रशंसापत्र", "नहीं es", "कहते हैं", "इंटरनेट में संसाधन", "यह भी देखें", "डेवो", "बाहर से लिंक करें", "उसके बारे में", "यह भी देखें", "फिल्म", "पर", "संदर्भ", "उन्होंने कहा ओ", "संबंधित", "बाहरी लिंक", "बयानों के बारे में", "के बारे में", "उपरोक्त उद्धरण", "स्रोत", "राजदूत", "यह उसे कहा जाता है", "साहित्य", "अपने बारे में", "बाहरी लिंक", "संबंधित अनुप्रयोग", "के संबंध में उद्धरण", "देखें", "ओवर", "अतिरिक्त लिंक", "उद्धरण के बारे में", "फिल्मोग्राफी", "फुटनोट", " स्रोत", "संसाधन", "अन्य परियोजनाएं", "बाहरी लिंक", "लिंक", "नोट्स", "नोट", "वेबलिंक", "ग्रंथ सूची", "संबंधित आइटम", "कार्य", "संदर्भ", "साहित्य", "देखें", "यह भी देखें", "फुटनोट", "अन्य परियोजनाएं"]
forbidden_by_language["hr"] = ["navodnici o", "filmografija", "fusnota", "izvori", "izvori", "drugi projekti", "vanjske veze", "veze", "bilješke", "napomena", "weblinks", "bibliografija", "srodne stavke", "radovi", "reference", "literatura", "vidi", "vidi također", "fusnota", "drugi projekti", "također pogledajte", "Bibliografija", "radovi", "Zapaženo", "referenca", "Još jedan o tome", "u obljetnici", "rekli su o tome", "Filmografija", "Kaže se", "linkovi", "Rekli su o njemu", "Jesu li rekao o", "citati", "Veza na", "preporuke", "Najpoznatije knjige", "Vanjski tad", "Vanjske veze", "Izvori:", "o njemu", "ovisni upiti", " Referenca", "Sinhronizacija", "filmografija", "za njega", "O", "Vanjske veze", "predstave", "fusnota", "rečeno je o njemu", "Djela", "Predstave", " na", "Drugi projekti", "O njoj", "O njoj", "Resursi", "Vanjski link", "reference", "Izvori", "Rečeno je o njoj", "fusnote", "Vanjske reference", "Povezane stavke", "Izvor", "Napomene:", "Veze", "Za nju", "Izdanja", "Izjave", "Ne es", "recimo", "resursi na Internetu", "Vidi također", "daveoù", "Veza prema van", "O njemu", "vidi također", "film", "on", "Reference", "Rekli su O.", "Povezano", "vanjska veza", "Izjave o", "o", "Navodi gore", "izvori", "Ambasador", "Rečeno mu je", "književnost", "o sebi", "vanjske veze", "Povezane aplikacije", "Citati s obzirom na", "Vidi", "preko", "Višak veza", "citati o", "filmografija", "fusnota", " izvori", "resursi", "ostali projekti", "vanjske veze", "veze", "bilješke", "bilješka", "web-veze", "bibliografija", "srodne stavke", "radovi", "reference", "književnost", "vidi", "vidi također", "fusnota", "drugi projekti"]
forbidden_by_language["is"]  = ["tilvitnanir um", "kvikmyndafræði", "neðanmálsgrein", "heimildir", "auðlindir", "önnur verkefni", "ytri tenglar", "tenglar", "aths", "ath", "weblinks", "heimildaskrá", "tengd atriði", "verk", "tilvísanir", "bókmenntir", "sjá", "sjá einnig", "neðanmálsgrein", "önnur verkefni", "Skoðaðu líka", "Heimildaskrá", "verk", "Athyglisvert", "tilvísun", "Annað um það", "í afmælinu", "þeir sögðu um það", "Kvikmyndataka", "Seggja við", "tenglar", "Þeir sögðu um hann", "Eru sagði um", "tilvitnanir", "Tengill á", "tilvísanir", "Frægustu bækurnar", "Ytri tads", "Ytri tengingar", "Heimildir:", "um hann", "háðar fyrirspurnir", " Tilvísun", "talsetning", "kvikmyndataka", "fyrir hann", "O", "Ytri hlekkir", "leikrit", "neðanmálsgrein", "það var sagt um hann", "verk", "leikrit", " á", "Önnur verkefni", "Um", "um hana", "Auðlindir", "Ytri tengill", "tilvísanir", "Heimildir", "Það var sagt um hana", "neðanmálsgrein", "Ytri tilvísanir", "Tengd atriði", "Heimild", "Athugasemdir:", "Tenglar", "Fyrir hana", "Útgáfur", "Vitnisburður", "Ekki es", "segja", "tilföng á internetinu", "Sjá líka", "daveoù", "Tengill að utan", "Um hann", "sjá líka", "kvikmynd", "on", "Tilvísanir", "Þeir sögðu O.", "Tengd", "ytri tengill", "Yfirlýsingar um", "um", "Tilvitnanir að ofan", "heimildir", "sendiherra", "það er sagt við hann", "bókmenntir", "um sjálfa sig", "ytri tenglar", "Tengd forrit", "Tilvitnanir með tilliti til", "Sjá", "yfir", "Umframtenglar", "tilvitnanir um", "kvikmyndafræði", "neðanmáls", " heimildir", "tilföng", "önnur verkefni", "ytri hlekkir", "tenglar", "athugasemdir", "aths", "veftenglar", "heimildaskrá", "tengd atriði", "verk", "tilvísanir", "bókmenntir", "sjá", "sjá einnig", "neðanmálsgrein", "önnur verkefni"]
forbidden_by_language["it"] = ["citazioni su", "filmografia", "nota", "fonti", "risorse", "altri progetti", "link esterni", "link", "note", "nota", "link web", "bibliografia", "articoli correlati", "opere", "riferimenti", "letteratura", "vedi", "vedi anche", "nota a piè di pagina", "altri progetti", "guarda anche", "bibliografia", "lavori", "Notevole", "riferimento", "Un altro a riguardo", "nell'anniversario", "hanno detto a riguardo", "Filmografia", "Detto a", "link", "Hanno detto di lui", "Sono ha detto su", "citazioni", "Link a", "riferimenti", "I libri più famosi", "Schede esterne", "Connessioni esterne", "Fonti:", "su di lui", "domande dipendenti", " Riferimento", "Doppiaggio", "filmografia", "per lui", "O", "Link esterni", "ascolta", "nota a piè di pagina", "si diceva di lui", "Lavori", "Riproduzioni", " su", "Altri progetti", "Su", "su di lei", "Risorse", "Link esterno", "riferimenti", "Fonti", "Si diceva di lei", "note a piè di pagina", "Riferimenti esterni", "Articoli correlati", "Fonte", "Note:", "Link", "Per lei", "Pubblicazioni", "Testimonianze", "Non es", "say", "risorse in Internet", "Vedi anche", "daveoù", "Link all'esterno", "Su di lui", "vedi anche", "film", "on", "Riferimenti", "Hanno detto O.", "Correlato", "link esterno", "Dichiarazioni su", "su", "Citazioni sopra", "fonti", "Ambasciatore", "Si dice a lui", "letteratura", "su di sé", "link esterni", "applicazioni correlate", "citazioni rispetto a", "vedere", "sopra", "collegamenti in eccesso", "citazioni su", "filmografia", "nota a piè di pagina", " fonti", "risorse", "altri progetti", "link esterni", "link", "note", "nota", "link web", "bibliografia", "articoli correlati", "lavori", "riferimenti", "letteratura", "vedi", "vedi anche", "nota a piè di pagina", "altri progetti"]
forbidden_by_language["ja"] = ["引用'、 '脚注'、 'ソース'、 'リソース'、 'その他のプロジェクト'、 '外部リンク'、 'リンク'、 'ノート'、 '注'、 'ウェブリンク'、 '参考文献' ' '、'作品 '、'参考文献 '、'文学 '、'参照 '、'関連項目 '、'脚注 '、'その他のプロジェクト '、'関連項目 '、'参考文献 '、'作品 ' 、 '注目すべき'、 '参照'、 'それについての別の'、 '記念日'、 '彼らはそれについて言った'、 '映画誌'、 '言っている'、 'リンク'、 '彼らは彼について言った'、 ' '、'引用符 '、'リンク先 '、'参照 '、'最も有名な本 '、'外部接続 '、'外部接続 '、'出典： '、'彼について '、'依存クエリ '、'参照 '、'ダビング '、'フィルムグラフィー '、'彼のために '、' O '、'外部リンク '、'演劇 '、'脚注 '、'彼について言われた '、'作品 '、'演劇 '、' '、'その他のプロジェクト '、'について '、'彼女について '、'リソース '、'外部リンク '、'参照 '、'ソース '、'彼女について言われた '、'脚注 '、'外部参照 ' 、 '関連項目'、 'ソース'、 '注：'、 'リンク'、 '彼女のために'、 'リリース'、 '証言","脚注'、 '言う'、 'インターネットのリソース'、 '関連項目' 、、 '外部へのリンク'、 '彼について'、 '関連項目'、 '映画'、 '参考文献'、 '参照はO '、'リソース'、 '映画リンク'、 'リンク'、 '注'、 '注'、 'レリンク'、 '参照参照'、 '化参照'、 '作品 '、'参照 '、'文献 '、'参照 '、'関連項目 '、'脚注 '、'その他のプロジェクト "]
forbidden_by_language["ka"] = ["ციტატები", "ფილმოგრაფია", "სქოლიო", "წყაროები", "რესურსები", "სხვა პროექტები", "გარე ბმულები", "ბმულები", "შენიშვნები", "შენიშვნა", "ვებლინკები", "ბიბლიოგრაფია'", "დაკავშირებული ერთეულები", "ნამუშევრები", "ცნობები", "ლიტერატურა", "იხილეთ", "ასევე იხილეთ", "სქოლიო", "სხვა პროექტები", "ასევე შეხედე", "ბიბლიოგრაფია", "ნამუშევრები' , „აღსანიშნავი“, „მინიშნება“, „კიდევ ერთი ამის შესახებ“, „იუბილეზე“, „ამის შესახებ თქვეს“, „ფილმოგრაფია“, „ამბობენ“, „ბმულები“, „მასზე თქვეს“, „არის. ნათქვამია შესახებ", "ციტატები", "ბმული", "რეფერატები", "ყველაზე ცნობილი წიგნები", "გარე ბავშვები", "გარე კავშირები", "წყაროები:", "მის შესახებ", "დამოკიდებული შეკითხვები", " მითითება“, „დუბლირება“, „ფილმოგრაფია“, „მისთვის“, „ო“, „გარე ბმულები“, „სპექტაკლები“, „სქოლიო“, „მასზე ითქვა“, „ნამუშევრები“, „სპექტაკლები“, „ საფუძველზე", "სხვა პროექტები", "შესახებ", "მის შესახებ", "რესურსები", "გარე ბმული", "ცნობები", "წყაროები", "ითქვა მის შესახებ", "სქოლიოები", "გარე ცნობები", "დაკავშირებული ნივთები", "წყარო", "შენიშვნები:", "ბმულები", "მისთვის", "გამოშვებები", "ჩვენებები", "N ოტესები", "ვთქვათ", "რესურსები ინტერნეტში", "ასევე იხილეთ", "დავეოუ", "გარედან ბმული", "მის შესახებ", "ასევე იხილეთ", "ფილმი", "ჩართული", "ცნობები", "მათ თქვეს ო.", "დაკავშირებული", "გარე ბმული", "განცხადებები", "შესახებ", "ციტატები ზემოთ", "წყაროები", "ელჩი", "მას უთხრეს", "ლიტერატურა", "თავის შესახებ", "გარე ბმულები", "დაკავშირებული აპლიკაციები", "ციტატები დაკავშირებით", "იხილეთ", "ზედა", "ჭარბი ბმულები", "ციტატები", "ფილმოგრაფია", "სქოლიო", " წყაროები", "რესურსები", "სხვა პროექტები", "გარე ბმულები", "ბმულები", "შენიშვნები", "შენიშვნა", "ვებლინკები", "ბიბლიოგრაფია", "დაკავშირებული ერთეულები", "ნამუშევრები", "ცნობები", "ლიტერატურა", "იხილეთ", "ასევე იხილეთ", "სქოლიო", "სხვა პროექტები"]
forbidden_by_language["pl"] = ['zobacz też', 'o ', 'Zasoby', 'Wydanie', 'o nim', 'Link do zewnątrz', 'Cytaty w odniesieniu do', 'Bibliografia', 'Najbardziej znane książki', 'powiedzieli o tym', 'Powiedziane są o', 'Powiązane przedmioty', 'na', 'spinki do mankietów', 'Powiązane zastosowania', 'referencja', 'Powiedzieli o nim', 'Również patrzeć', 'Pracuje', 'literatura', 'Link zewnętrzny', 'Referencje.', 'Bibliografia', 'zależało zapytania', 'Daveoù.', 'Powiedział o niej', 'Spinki do mankietów', 'Pracuje', 'Uwagi:', 'Dubbing.', 'przypisy', 'Widzieć', 'Mówiono o nim', 'o niej', 'Ambasador', 'cytaty', 'bawić się', 'film', 'O.', 'Filmografia', 'O nim', 'Związane z', 'Zewnętrzne odniesienia', 'Cytaty powyżej', 'link zewnętrzny', 'Bibliografia', 'Inne projekty', 'Filmografia', 'Outer Tads.', 'Źródło', 'Zewnętrzne linki', 'Zasoby w Internecie.', 'notatka', 'Zobacz też', 'Referencja', 'Powiedzieli O.', 'Notatki', 'Dla niej', 'Znaczny', 'nad', 'Mówi się mu', 'Nadmiarowe linki', 'o', 'O sobie', 'Bawić się', 'ŹRÓDŁA', 'mowić', 'Inny o tym', 'Mówiąc do', 'Połączenia zewnętrzne', 'Zobacz też', 'od', 'O', 'w rocznicy.', 'Łączyć z', 'skierowania', 'dla niego', 'Źródła:', 'Oświadczenia o', 'ŹRÓDŁA', 'Zewnętrzne linki', 'cytaty', 'Filmografia', 'notatka', 'ŹRÓDŁA', 'Surowce', 'inne projekty', 'Zewnętrzne linki', 'spinki do mankietów', 'notatki', 'Notatka', 'linki internetowe', 'bibliografia', 'powiązane przedmioty', 'Pracuje', 'Bibliografia', 'literatura', 'zobaczyć', 'Zobacz też', 'notatka', 'inne projekty']
forbidden_by_language["ro"] = ['legături externe', 'despre', 'NOTE:', 'literatură', 'sa spus despre el', 'despre el', 'Dobbing.', 'Pentru ea', 'Se spune despre', 'Articole conexe', 'Notabil', 'Notele de subsol', 'Aplicații înrudite', 'Filmografie', 'Surse:', 'depinde de interogări', 'Referințe externe', 'Au spus despre el', 'Alte proiecte', 'Vedea', 'Uitați de asemenea la', 'Filmografie', 'Despre', 'pe', 'Legate de', 'O.', 'Ambasador', 'joacă', 'referinţă', 'pentru el', 'TADS OUTER.', 'Bibliografie', 'linkuri externe', 'În aniversare', 'Link-uri', 'Releases.', 'despre ea însăși', 'Link-uri', 'lucrări', 'Referinţă', 'Declarații despre', 'Vezi si', 'Cele mai cunoscute cărți', 'Lucrări', 'Sa spus despre ea', 'Link-uri excesive', 'citate', 'Link-ul la exterior', 'Sursă', 'Altul despre el', 'Spunând', 'film', 'Citate cu privire la', 'Spune', 'Daveoù.', 'Link extern', 'Citări de mai sus', 'Vezi si', 'peste', 'Surse.', 'Îi se spune', 'Au spus O.', 'Referințe', 'despre', 'peste', 'Legătura cu', 'Joacă', 'Referințe', 'despre ea', 'Surse.', 'linkuri externe', 'Au spus despre asta', 'Link extern', 'Mărturii', 'notă de subsol', 'Referințe', 'Note', 'Resurse pe Internet', 'Despre el', 'Resurse', 'Conexiuni externe', 'Citate despre', 'Filmografie', 'notă de subsol', 'Surse.', 'resurse', 'Alte proiecte', 'linkuri externe', 'Link-uri', 'note', 'Notă', 'Link-uri web', 'bibliografie', 'Articole conexe', 'lucrări', 'Referințe', 'literatură', 'vedea', 'Vezi si', 'notă de subsol', 'Alte proiecte']
forbidden_by_language["ru"] = ['Об ', 'Фильмография', 'примечания', 'ссылки ', 'см. также', 'Примечания:', 'литература', 'Было сказано о нем', 'о нем', 'Дублировка', 'Для нее', 'Говорится о', 'Похожие материалы', 'нотенно', 'сноски', 'Похожие приложения', 'Фильмография', 'Источники:', 'Взял запросы', 'Внешние ссылки', 'Они сказали о нем', 'Другие проекты', 'Видеть', 'Также смотрите', 'фильмография', 'О', 'на', 'Связанный', 'О', 'Посол', 'пьесы', 'ссылка', 'для него', 'Внешние тады', 'Библиография', 'внешние ссылки', 'в годовщине', 'Ссылки', 'Релизы', 'о себе', 'ссылки', 'работает', 'Ссылка', 'Утверждение о', 'смотрите также', 'Самые известные книги', 'Работает', 'Было сказано о ней', 'Избыточные ссылки', 'Ссылка на улицу', 'Источник', 'Другой об этом', 'Говорить', 'пленка', 'Цитаты по отношению к', 'сказать', 'Daveoù.', 'Внешняя ссылка', 'Цитаты выше', 'Смотрите также', 'над', 'Источники', 'Это сказано ему', 'Они сказали О.', 'использованная литература', 'о', 'на', 'Ссылка на', 'Пьесы', 'рефералы', 'о ней', 'источники', 'внешние ссылки', 'Они сказали об этом', 'внешняя ссылка', 'Отзывы', 'сноска', 'использованная литература', 'Примечания', 'Ресурсы в интернете', 'О нем', 'Ресурсы', 'Внешние соединения', 'цитаты о', 'фильмография', 'сноска', 'источники', 'Ресурсы', 'другие проекты', 'внешние ссылки', 'ссылки', 'Примечания', 'Примечание', 'веб ссылки', 'Библиография', 'Похожие материалы', 'работает', 'использованная литература', 'литература', 'видеть', 'смотрите также', 'сноска', 'другие проекты']
forbidden_by_language["sk"] = ['Povedali o', 'iné projekty', 'referencie', 'Poznámky:', 'literatúra', 'Hovorilo sa o ňom', 'o ňom', 'Dabovanie', 'Pre ňu', 'Hovoria', 'Súvisiace položky', 'Pozoruhodný', 'poznámky pod čiarou', 'Súvisiace aplikácie', 'Filmograf', 'Zdroje:', 'závislé dotazy', 'Externé referencie', 'Povedali o ňom', 'Ostatné projekty', 'Pozrieť sa', 'Pozrite sa aj na', 'filmograf', 'O', 'zapnutý', 'Súvisiaci', 'O', 'Veľvyslanec', 'hrať', 'referencia', 'pre neho', 'Vonkajšie tads', 'Bibliografia', 'vonkajšie odkazy', 'v výročnom', 'Spojenie', 'Vydania', 'o sebe', 'spojenie', 'Tvorba', 'Referencia', 'Vyhlásenia', 'pozri tiež', 'Najznámejšie knihy', 'Tvorba', 'Povedala sa o ňom', 'Prebytočné odkazy', 'citácie', 'Odkaz na vonkajšiu stranu', 'Zdroj', 'O tom', 'Hovoriť', 'film', 'Citáty s ohľadom na', 'povedať', 'daveoù', 'Externý odkaz', 'Vyššie uvedené citácie', 'Pozri tiež', 'nad', 'Zdroje', 'Hovorí sa mu', 'Povedali o.', 'Referencie', 'o', 'na', 'Odkaz na', 'Hrať', 'referencie', 'o nej', 'zdroje', 'vonkajšie odkazy', 'Povedali o tom', 'externý odkaz', 'Referencie', 'poznámka pod čiarou', 'referencie', 'Poznámky', 'Zdroje na internete', 'O ňom', 'Prostriedky', 'Externé pripojenia', 'cituje', 'filmograf', 'poznámka pod čiarou', 'zdroje', 'prostriedky', 'Ostatné projekty', 'vonkajšie odkazy', 'spojenie', 'poznámky', 'Poznámka', 'weblinks', 'Bibliografia', 'Súvisiace položky', 'Tvorba', 'referencie', 'literatúra', 'pozrieť sa', 'pozri tiež', 'poznámka pod čiarou', 'Ostatné projekty']
forbidden_by_language["sl"] = ['viri', 'sklici', 'Opombe:', 'Literatura.', 'Rečeno je bilo o njem', 'o njem', 'Dubbing.', 'Za njo', 'Rečeno', 'Podobni elementi', 'Opazno', 'Opombe', 'Povezane aplikacije', 'Filmografija', 'Viri:', 'odvisne poizvedbe', 'Zunanje reference', 'Rekli so o njem', 'Drugi projekti', 'Glejte', 'Oglejte si tudi', 'filmografija', 'Približno', 'On.', 'Povezano', 'O.', 'Veleposlanik', 'igra', 'Referenca', 'zanj', 'Zunanji tads.', 'Bibliografija', 'Zunanje povezave', 'V obletnici', 'Povezave', 'Sprosti', 'o sebi', 'Povezave', 'dela', 'Referenca', 'Izjave', 'Poglej tudi', 'Najbolj znane knjige', 'Dela', 'Rečeno je bilo o njej', 'Presežne povezave', 'citate', 'Povezava na zunanjost', 'Vir.', 'Drugo o tem', 'Rekel', 'film', 'Citati v zvezi s tem', 'reči.', 'daveoù.', 'Zunanja povezava', 'Zgoraj', 'Poglej tudi', 'nad', 'Viri', 'Rečeno mu je', 'Rekli so O.', 'Reference', 'približno', 'AN.', 'Povezava do', 'Igra', 'napotitve', 'o njej', 'Viri', 'Zunanje povezave', 'Rekli so o tem', 'Zunanja povezava', 'Pričevanja', 'opomba', 'Reference', 'Opombe', 'Viri na internetu', 'O njem', 'Viri', 'Zunanje povezave', 'navaja', 'filmografija', 'opomba', 'Viri', 'Viri', 'Drugi projekti', 'Zunanje povezave', 'Povezave', 'Opombe', 'Opomba', 'weblinks.', 'Bibliografija', 'Podobni elementi', 'dela', 'Reference', 'Literatura.', 'Glejte', 'Poglej tudi', 'opomba', 'Drugi projekti']
forbidden_by_language["sq"] = ['Thënie për të', 'Referimet', 'Shiko edhe', 'lidhje të jashtme', 'referime', 'Shënime:', 'letërsi', 'U tha për të', 'për të', 'Dublim', 'Për të', 'Janë thënë', 'Artikuj të ngjashëm', 'I dukshëm', 'fusnotat', 'Aplikime të ngjashme', 'Film', 'Burimet:', 'Pyetje të varura', 'Referencat e jashtme', 'Ata thanë për të', 'Projekte të tjera', 'Shiko', 'Gjithashtu shikoni', 'film', 'Rreth', 'në', 'I lidhur', 'O', 'Ambasador', 'luaj', 'referim', 'per atë', 'Tads e jashtme', 'Bibliografi', 'Linqe te jashtme', 'Në përvjetorin', 'Lidhje', 'Liron', 'për veten', 'lidhje', 'vepron', 'Referim', 'Deklaratat rreth', 'Shiko gjithashtu', 'Librat më të famshëm', 'Vepron', 'U tha për të', 'Lidhje të tepërta', 'kuotat', 'Lidhje me pjesën e jashtme', 'Burim', 'Një tjetër për këtë', 'Duke thënë', 'film', 'Kuotat në lidhje me', 'thua', 'daveoù', 'Lidhje e jashtme', 'Citimet e mësipërme', 'Shiko gjithashtu', 'mbi', 'Burime', 'Është thënë atij', 'Ata thanë O.', 'Referencat', 'rreth', 'në', 'Lidh me', 'Luaj', 'referime', 'për të', 'burime', 'Linqe te jashtme', 'ata thanë për këtë', 'lidhje e jashtme', 'Dëshmi', 'shënim shënim', 'referencat', 'Shënim', 'Burimet në Internet', 'Për të', 'Burime', 'Lidhjet e jashtme', 'citon rreth', 'film', 'shënim shënim', 'burime', 'burime', 'Projekte të tjera', 'Linqe te jashtme', 'lidhje', 'shënim', 'shënim', 'weblinks', 'bibliografi', 'Artikuj të ngjashëm', 'vepron', 'referencat', 'letërsi', 'Shiko', 'Shiko gjithashtu', 'shënim shënim', 'Projekte të tjera']
forbidden_by_language["ta"] = ['வெளி இணைப்புகள்', 'சான்றுகள்', 'குறிப்புகள்:', 'இலக்கியம்', 'அது அவரைப் பற்றி கூறப்பட்டது', 'அவரை பற்றி', 'டுபிங்', 'அவளுக்கு', 'பற்றி கூறப்படுகிறது', 'தொடர்புடைய பொருட்கள்', 'குறிப்பிடத்தக்கது', 'அடிக்குறிப்புகள்', 'தொடர்புடைய பயன்பாடுகள்', 'திரைப்படவியல்', 'ஆதாரங்கள்:', 'சார்ந்த கேள்விகள்', 'வெளிப்புற குறிப்புகள்', 'அவர்கள் அவரைப் பற்றி சொன்னார்கள்', 'பிற திட்டங்கள்', 'பார்க்க', 'மேலும் பாருங்கள்', 'திரைப்படவியல்', 'பற்றி', 'மீது', 'தொடர்புடைய', 'ஓ', 'தூதர்', 'நாடகம்', 'குறிப்பு', 'அவருக்கு', 'வெளிப்புற tads.', 'நூலகம்', 'வெளி இணைப்புகள்', 'ஆண்டு விழாவில்', 'இணைப்புகள்', 'வெளியீடுகள்', 'தன்னை பற்றி', 'இணைப்புகள்', 'வேலை', 'குறிப்பு', 'பற்றி அறிக்கைகள்', 'மேலும் காண்க', 'மிகவும் பிரபலமான புத்தகங்கள்', 'வேலை', 'அது அவளைப் பற்றி கூறப்பட்டது', 'அதிக இணைப்புகள்', 'மேற்கோள்கள்', 'வெளியே இணைப்பு', 'மூல', 'அது பற்றி மற்றொரு', 'சொல்லுங்கள்', 'திரைப்படம்', 'மரியாதையுடன் மேற்கோள்கள்', 'சொல்', 'daveoù.', 'வெளிப்புற இணைப்பு', 'மேலே மேற்கோள்கள்', 'மேலும் காண்க', 'மேல்', 'ஆதாரங்கள்', 'அது அவரிடம் கூறப்படுகிறது', 'அவர்கள் ஓ என்று சொன்னார்கள்.', 'குறிப்புகள்', 'பற்றி', 'மீது', 'இணைப்பு', 'நாடகம்', 'பரிந்துரைகளை', 'அவளை பற்றி', 'ஆதாரங்கள்', 'வெளி இணைப்புகள்', 'அவர்கள் அதைப் பற்றி சொன்னார்கள்', 'வெளிப்புற இணைப்பு', 'சான்றுகள்', 'அடிகுறிப்பு', 'குறிப்புகள்', 'குறிப்புகள்', 'இணையத்தில் வளங்கள்', 'அவரை பற்றி', 'வளங்கள்', 'வெளிப்புற இணைப்புகள்', 'மேற்கோள்கள் பற்றி', 'திரைப்படவியல்', 'அடிகுறிப்பு', 'ஆதாரங்கள்', 'வளங்கள்', 'பிற திட்டங்கள்', 'வெளி இணைப்புகள்', 'இணைப்புகள்', 'குறிப்புகள்', 'குறிப்பு', 'weblinks.', 'நூலகம்', 'தொடர்புடைய பொருட்கள்', 'வேலை', 'குறிப்புகள்', 'இலக்கியம்', 'பார்க்க', 'மேலும் காண்க', 'அடிகுறிப்பு', 'பிற திட்டங்கள்']
forbidden_by_language["te"] = ['మూలాలు', 'గమనికలు:', 'సాహిత్యం', 'ఇది అతని గురించి చెప్పబడింది', 'అతని గురించి', 'డబ్బింగ్', 'ఆమె కోసం', 'గురించి చెప్పారు', 'సంబంధిత అంశాలు', 'గుర్తించదగినది', 'ఫుట్నోట్స్', 'సంబంధిత అనువర్తనాలు', 'ఫిల్మోగ్రఫీ', 'సోర్సెస్:', 'వివరించిన ప్రశ్నలు', 'బాహ్య సూచనలు', 'వారు అతని గురించి చెప్పారు', 'ఇతర ప్రాజెక్టులు', 'చూడండి', 'కూడా చూడండి', 'ఫిల్మోగ్రఫీ', 'గురించి', 'పై', 'సంబంధిత', 'O.', 'రాయబారి', 'ప్లేస్', 'సూచన', 'అతనికి', 'ఔటర్ tads.', 'బిబ్లియోగ్రఫీ', 'బాహ్య లింకులు', 'వార్షికోత్సవంలో', 'లింకులు', 'విడుదలలు', 'ఆమె గురించి', 'లింకులు', 'పనిచేస్తుంది', 'సూచన', 'గురించి ప్రకటనలు', 'ఇది కూడ చూడు', 'అత్యంత ప్రసిద్ధ పుస్తకాలు', 'పనిచేస్తుంది', 'ఆమె గురించి చెప్పబడింది', 'అదనపు లింకులు', 'కోట్స్', 'వెలుపల లింక్', 'మూల', 'దాని గురించి మరొకటి', 'చెప్పడం', 'సినిమా', 'సంబంధించి కోట్స్', 'చెప్పండి', 'daveoù.', 'బాహ్య లింక్', 'పైన ఉన్న అనులేఖనాలు', 'ఇది కూడ చూడు', 'పైగా', 'సోర్సెస్', 'అది అతనికి చెప్పబడింది', 'వారు ఓ అన్నారు', 'ప్రస్తావనలు', 'గురించి', 'దీని తరువాత', 'లింక్', 'ప్లేస్', 'రెఫరల్స్', 'ఆమె గురించి', 'సోర్సెస్', 'బాహ్య లింకులు', 'వారు దాని గురించి చెప్పారు', 'బాహ్య లింక్', 'టెస్టిమోనియల్స్', 'ఫుట్నోట్', 'ప్రస్తావనలు', 'గమనికలు', 'ఇంటర్నెట్లో వనరులు', 'అతని గురించి', 'వనరులు', 'బాహ్య కనెక్షన్లు', 'కోట్స్ గురించి', 'ఫిల్మోగ్రఫీ', 'ఫుట్నోట్', 'సోర్సెస్', 'వనరులు', 'ఇతర ప్రాజెక్టులు', 'బాహ్య లింకులు', 'లింకులు', 'గమనికలు', 'గమనిక', 'weblinks.', 'బిబ్లియోగ్రఫీ', 'సంబంధిత అంశాలు', 'పనిచేస్తుంది', 'ప్రస్తావనలు', 'సాహిత్యం', 'చూడండి', 'ఇది కూడ చూడు', 'ఫుట్నోట్', 'ఇతర ప్రాజెక్టులు']
forbidden_by_language["tr"] = ['Hakkında', 'kaynakça', 'Notlar:', 'Edebiyat', 'Onun hakkında söylendi', 'onun hakkında', 'Dublaj', 'Onun için', 'Hakkında söyleniyor', 'İlgili öğeler', 'Dikkate değer', 'dipnotlar', 'İlgili uygulamalar', 'Filmografi', 'Kaynaklar:', 'SORUMLULUKLAR', 'Dış referanslar', 'Onun hakkında söylediler', 'Diğer projeler', 'Görmek', 'Ayrıca bak', 'filmografi', 'Hakkında', 'üzerinde', 'İlgili', 'Ö', 'Büyükelçi', 'oynar', 'referans', 'onun için', 'Dış tads', 'Bibliyografya', 'Dış bağlantılar', 'yıldönümünde', 'Linkler', 'Salıverme', 'kendisi hakkında', 'linkler', 'İşler', 'Referans', 'Hakkında açıklamalar', 'Ayrıca bakınız', 'En ünlü kitaplar', 'İşler', 'Onun hakkında söylendi', 'Aşırı bağlantılar', 'alıntı', 'Dışa bağlantı', 'Kaynak', 'Bunun hakkında başka', 'Söyleyerek', 'film', 'İle ilgili alıntılar', 'söylemek', 'Daveoù', 'Harici bağlantı', 'Yukarıdaki alıntılar', 'Ayrıca bakınız', 'üzerinde', 'Kaynaklar', 'Ona söyleniyor', 'O dediler.', 'Referanslar', 'hakkında', 'üzerine', 'Bağlamak', 'Oynar', 'yönlendirmeler', 'Onun hakkında', 'kaynaklar', 'Dış bağlantılar', 'Bunun hakkında söylediler', 'harici bağlantı', 'Tanıklık', 'dipnot', 'Referanslar', 'Notlar', 'İnternetteki kaynaklar', 'Onun hakkında', 'Kaynaklar', 'Harici Bağlantılar', 'hakkında alıntılar', 'filmografi', 'dipnot', 'kaynaklar', 'Kaynaklar', 'diğer projeler', 'Dış bağlantılar', 'linkler', 'notalar', 'Not', 'İnternet linkleri', 'bibliyografya', 'ilgili öğeler', 'İşler', 'Referanslar', 'Edebiyat', 'görmek', 'Ayrıca bakınız', 'dipnot', 'diğer projeler']
forbidden_by_language["uk"] = ['Про ', 'Джерела', 'примітки', 'література', 'Примітки:', 'література', 'Про це сказано', 'про нього', 'Дублювання', 'Для неї', 'Сказані', "Пов'язані елементи", 'Нотен', 'виноски', "Пов'язані заявки", 'Фільмографія', 'Джерела:', 'залежати від запитів', 'Зовнішні посилання', 'Вони сказали про нього', 'Інші проекти', 'Побачити', 'Також подивіться', 'фільмографія', 'Про', 'на', 'Споріднений', 'O', 'Посла', 'грає', 'довідник', 'для нього', 'Зовнішні tads', 'Бібліографія', 'зовнішні посилання', 'у річницю', 'Посилання', 'Релізи', 'про себе', 'посилання', 'робіт', 'Довідник', 'Заяви про', 'Дивись також', 'Найвідоміші книги', 'Робіт', 'Це було сказано про неї', "Надлишкові зв'язки", 'котирування', 'Посилання назовні', 'Джерело', 'Інше про це', 'Кажуть', 'плівка', 'Цитати по відношенню до', 'казати', 'дав', 'Зовнішня посилання', 'Цитати вище', 'Дивись також', 'надмірно', 'Джерела', 'Йому сказано', 'Вони сказали О.', 'Посилання', 'про', 'на', 'Посилання на', 'Грає', 'рефераль', 'про неї', 'джерела', 'зовнішні посилання', 'вони сказали про це', 'Зовнішня посилання', 'Відгуки', 'виноска', 'посилання', 'Ноти', 'Ресурси в Інтернеті', 'Про нього', 'Ресурси', "Зовнішні з'єднання", 'фільмографія', 'виноска', 'джерела', 'ресурси', 'Інші проекти', 'зовнішні посилання', 'посилання', 'ноти', 'Примітка', 'weblinks', 'бібліографія', "Пов'язані елементи", 'робіт', 'посилання', 'література', 'побачити', 'Дивись також', 'виноска', 'Інші проекти']
forbidden_by_language["ur"] = ['حوالہ جات', 'نوٹ:', 'ادب', 'اس کے بارے میں یہ کہا گیا تھا', 'اس کے بارے میں', 'ڈوبنگ', 'اس لڑکی کے لئے', 'کے بارے میں کہا جاتا ہے', 'متعلقہ اشیاء', 'قابل ذکر', 'فوٹیاں', 'متعلقہ ایپلی کیشنز', 'فلمگرافی', 'ذرائع:', 'منحصر سوالات', 'بیرونی حوالہ جات', 'انہوں نے اس کے بارے میں کہا', 'دیگر منصوبوں', 'دیکھو', 'بھی دیکھو', 'فلمگرافی', 'کے بارے میں', 'پر', 'متعلقہ', 'اے', 'سفیر', 'ادا کرتا ہے', 'حوالہ', 'اس کے لیے', 'بیرونی ٹاد', 'بائبلگرافی', 'بیرونی روابط', 'سالگرہ میں', 'روابط', 'ریلیز', 'خود کے بارے میں', 'روابط', 'کام', 'حوالہ', 'کے بارے میں بیانات', 'بھی دیکھو', 'سب سے مشہور کتابیں', 'کام', 'اس کے بارے میں یہ کہا گیا تھا', 'اضافی لنکس', 'حوالہ جات', 'باہر سے رابطہ کریں', 'ذریعہ', 'اس کے بارے میں ایک اور', 'کہہ رہا ہے', 'فلم', 'احترام کے ساتھ حوالہ جات', 'کہہ دو', 'ڈیویو', 'بیرونی لنک', 'حوالہ اوپر', 'بھی دیکھو', 'زیادہ', 'ذرائع', 'اس سے کہا جاتا ہے', 'انہوں نے کہا اے', 'حوالہ جات', 'کے بارے میں', 'پر', 'سے رابطہ کریں', 'ادا کرتا ہے', 'حوالہ جات', 'اس کے بارے میں', 'ذرائع', 'بیرونی روابط', 'انہوں نے اس کے بارے میں کہا', 'بیرونی لنک', 'تعریف', 'فوٹیوٹ', 'حوالہ جات', 'نوٹس', 'انٹرنیٹ میں وسائل', 'اس کے بارے میں', 'حوالہ جات', 'بیرونی کنکشن', 'کے بارے میں حوالہ جات', 'فلمگرافی', 'فوٹیوٹ', 'ذرائع', 'حوالہ جات', 'دیگر منصوبوں', 'بیرونی روابط', 'روابط', 'نوٹس', 'نوٹ', 'ویب لنکس', 'بائبلگرافی', 'متعلقہ اشیاء', 'کام', 'حوالہ جات', 'ادب', 'دیکھو', 'بھی دیکھو', 'فوٹیوٹ', 'دیگر منصوبوں']
forbidden_by_language["zh"] = ["引用","片目","脚注","来源","资源","其他项目","外部链接","链接","注释","注释","网络链接","参考书目","相关项目","作品","参考文献","文献","参见","另见","脚注","其他项目","另看","参考书目","作品", "著名","参考","他们说的","电影","关于他","相关查询","参考","配音","电影","为他","外部链接","戏剧","脚注","有人说他","作品","戏剧","其他项目"]

forbidden = [f.lower() for l in list(forbidden_by_language.values()) for f in l]


class EntityWithQuotes:
    def __init__(self, entity, id, language):
        def getQuotesFromUnstructuredText(section, id, wikiquote_id):     
            def getQ(section, id):
                nonlocal quotes
                nonlocal n
                nonlocal level
                nonlocal section_titles
                section_titles = section_titles[:level]
                section_titles.append(section.title.text)
                for line in section.lines:
                    n+=1
                    quote = untemplatedQuote(section_titles, line, id, n, language, wikiquote_id)
                    quotes.update({quote.id:quote})
                for sec in section.sub_sections:
                    if sec.title.text.lower() in forbidden+[i+" "+wikiquote_id.lower() for i in forbidden]:
                        continue
                    level=level+1
                    getQ(sec, id)
                level=level-1  
                temp_quotes = dict(quotes)
                for quote_id in temp_quotes:
                    if not quotes[quote_id]:
                        del quotes[quote_id]

            quotes = {}
            n = 1
            level = 0
            section_titles = []
            getQ(section, id)
            return quotes

        def getQuotesFromTemplates(section, id, wikiquote_id):
            def getTempQ(section,  id):
                nonlocal quotes
                nonlocal n
                nonlocal level
                nonlocal section_titles
                section_titles = section_titles[:level]
                section_titles.append(section.title.text)
                for template in section.templates:
                    n+=1
                    templ = template.values
                    quote = templatedQuote(id, n, language, section_titles, wikiquote_id, **templ)
                    quotes.update({quote.id:quote})
                for sec in section.sub_sections:
                    if sec.title.text.lower() in  forbidden+[i+" "+wikiquote_id.lower() for i in forbidden]:
                        continue
                    level=level+1
                    getTempQ(sec, id)
                level=level-1  
                # filtering for empty Quotes using __bool__
                temp_quotes = dict(quotes)
                for quote_id in temp_quotes:
                    if not quotes[quote_id]:
                        del quotes[quote_id]

            quotes = {}
            n = 1
            level = 0
            section_titles = []
            getTempQ(section, id)
            return quotes

        self.lang=language
        self.entity = entity
        self.wikiquote_id = entity.wikiquote_id
        self.id = id
        self.quotes = dict()
        if self.lang in languages_with_templates:
            self.quotes = getQuotesFromTemplates(entity.main_section, id, self.wikiquote_id)
        elif self.lang in hybrid_languages:
            self.quotes = getQuotesFromTemplates(entity.main_section, id, self.wikiquote_id) 
            self.quotes.update(getQuotesFromUnstructuredText(entity.main_section, self.id, self.wikiquote_id))
        else:
            self.quotes = getQuotesFromUnstructuredText(entity.main_section, self.id, self.wikiquote_id)

class CompleteEntity():
    def __init__(self, id, entities):
        self.entities = entities
        self.wikiquoteIds = dict()
        self.wikiquotePageIds= dict()
        self.wikipediaIds= dict()
        for language in self.entities:
            self.wikiquoteIds.update({language:self.entities[language][0].entity.wikiquote_id})
            self.wikiquotePageIds.update({language:self.entities[language][0].entity.wikiquote_page_id})
            self.wikipediaIds.update({language:self.entities[language][0].entity.wikipedia_id})
        self.wikidata_id = id






"""
main_section can have lines and/or sub_sections, sub_sections can again have lines and/or subsections
once the first lines are found every other deeper line is just context information
i want to go deeper and deeper until i find a list of lines that is not empty, once i find this
i iterate through the list collecting text. this will be my quote_text (a list)
after this is done, I collect title of every sub_section on way to lines, and under it, and all lines 

entity.main_section.lines = [Line, Line, Line]
entity.main_section.lines[i].text = quote 

>>> e0.main_section.sub_sections[0].lines
[<model.line.Line object at 0x7f315f8afc40>]
>>> e0.main_section.sub_sections[0].sub_sections
[]
>>> e0.main_section.sub_sections[0].title
<model.line.Line object at 0x7f315f8afca0>
>>> e0.main_section.sub_sections[0].title.text
'Nenaveden izvor'
>>> e0.main_section.sub_sections[0].lines[0].text
'"Razuman i pravdoljubiv čovjek od sebe najprije počinje: sebe ispituje i smatra, sebe sudi i osuđuje, niti sebi prašta ako u čemu krivo ima."'


Section
Title: author
    Section
    Title: source named > meta | if sorce not named avoid?
        Line: quote
            link:
            link:
            link:
            line: meta
                footnote: meta
                external link:
"""
"""
section
title: author
    section
    title: quotes from literary works
        line
            line
        line
        line
"""